// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Script;
import LIB.Libreria;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>RP_GENERICO_01</b><br>
 * Generated     : <b>2014/08/19 10:36:57</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 <br>
 * 
 * @since  agosto 19, 2014
 * @author ccortes
 */
public abstract class RP_GENERICO_01Helper extends LIB.Libreria
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox 17.0
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox 17.0
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : svwCombinacCatalogos:btnAceptarComb
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : svwCombinacCatalogos:btnAceptarComb
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : svwAgregarInsumoPopUp:btnAceptarIns
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit2"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : svwAgregarInsumoPopUp:btnAceptarIns
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit2"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:btnAceptarIns
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit3"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:btnAceptarIns
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit3"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit4"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit4"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit5() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit5"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit5(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit5"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit6() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit6"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit6(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit6"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit7() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit7"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit7(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit7"), anchor, flags);
	}
	
	/**
	 * AgregarCombinaciónsubmit: with default state.
	 *		.id : svwCombinacCatalogos:idCpteBtnSecAgregar:cmbACCAgregar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_agregarCombinaciónsubmi() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_agregarCombinaciónsubmi"));
	}
	/**
	 * AgregarCombinaciónsubmit: with specific test context and state.
	 *		.id : svwCombinacCatalogos:idCpteBtnSecAgregar:cmbACCAgregar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_agregarCombinaciónsubmi(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_agregarCombinaciónsubmi"), anchor, flags);
	}
	
	/**
	 * Aprobarsubmit: with default state.
	 *		.id : idVerReqAprobacion:comp_BotonConfSeleccion_1:botonConfSelec_1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aprobarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aprobarsubmit"));
	}
	/**
	 * Aprobarsubmit: with specific test context and state.
	 *		.id : idVerReqAprobacion:comp_BotonConfSeleccion_1:botonConfSelec_1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aprobarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aprobarsubmit"), anchor, flags);
	}
	
	/**
	 * Buscarsubmit: with default state.
	 *		.id : svwBuscarInsumoSM:cbp1:cb1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit"));
	}
	/**
	 * Buscarsubmit: with specific test context and state.
	 *		.id : svwBuscarInsumoSM:cbp1:cb1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit"), anchor, flags);
	}
	
	/**
	 * Buscarsubmit: with default state.
	 *		.id : svwBuscarConceptoSM:cbp1:cb1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit2"));
	}
	/**
	 * Buscarsubmit: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:cbp1:cb1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit2"), anchor, flags);
	}
	
	/**
	 * Buscarsubmit: with default state.
	 *		.id : idTmpB:componenteBotonBuscar:boton_buscar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit3"));
	}
	/**
	 * Buscarsubmit: with specific test context and state.
	 *		.id : idTmpB:componenteBotonBuscar:boton_buscar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit3"), anchor, flags);
	}
	
	/**
	 * ConfirmarSelecciónsubmit: with default state.
	 *		.id : svwBuscarInsumoSM:idCompBotonConfSeleccion:idCmbIrConfirmar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi"));
	}
	/**
	 * ConfirmarSelecciónsubmit: with specific test context and state.
	 *		.id : svwBuscarInsumoSM:idCompBotonConfSeleccion:idCmbIrConfirmar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi"), anchor, flags);
	}
	
	/**
	 * ConfirmarSelecciónsubmit: with default state.
	 *		.id : svwBuscarConceptoSM:idCompBotonConfSeleccion:idCmbIrConfirmar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi2"));
	}
	/**
	 * ConfirmarSelecciónsubmit: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:idCompBotonConfSeleccion:idCmbIrConfirmar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi2"), anchor, flags);
	}
	
	/**
	 * CrearDetallesubmit: with default state.
	 *		.id : idPgTpl:cbsCrearDetalle:claddct
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_crearDetallesubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_crearDetallesubmit"));
	}
	/**
	 * CrearDetallesubmit: with specific test context and state.
	 *		.id : idPgTpl:cbsCrearDetalle:claddct
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_crearDetallesubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_crearDetallesubmit"), anchor, flags);
	}
	
	/**
	 * Generarsubmit: with default state.
	 *		.id : idPgTpl:componenteBotonGenerarRequerimiento:botonGenerarRequerimiento
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_generarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_generarsubmit"));
	}
	/**
	 * Generarsubmit: with specific test context and state.
	 *		.id : idPgTpl:componenteBotonGenerarRequerimiento:botonGenerarRequerimiento
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_generarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_generarsubmit"), anchor, flags);
	}
	
	/**
	 * Ingresarsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Ingresar
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_ingresarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_ingresarsubmit"));
	}
	/**
	 * Ingresarsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Ingresar
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_ingresarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_ingresarsubmit"), anchor, flags);
	}
	
	/**
	 * IrALaBandejaDeEntradasubmit: with default state.
	 *		.id : pt2:idComponenteBotonRepetir:botonRepetir
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_irALaBandejaDeEntradasu() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_irALaBandejaDeEntradasu"));
	}
	/**
	 * IrALaBandejaDeEntradasubmit: with specific test context and state.
	 *		.id : pt2:idComponenteBotonRepetir:botonRepetir
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_irALaBandejaDeEntradasu(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_irALaBandejaDeEntradasu"), anchor, flags);
	}
	
	/**
	 * svwBuscarConceptoSMSmcConceptosEncontrados0: with default state.
	 *		.id : svwBuscarConceptoSM:smcConceptosEncontrados:_0
	 * 		.type : checkbox
	 * 		.value : 0
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarConceptoSM:smcConceptosEncontrados
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarConceptoSMSm() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarConceptoSMSm"));
	}
	/**
	 * svwBuscarConceptoSMSmcConceptosEncontrados0: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:smcConceptosEncontrados:_0
	 * 		.type : checkbox
	 * 		.value : 0
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarConceptoSM:smcConceptosEncontrados
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarConceptoSMSm(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarConceptoSMSm"), anchor, flags);
	}
	
	/**
	 * svwBuscarInsumoSMSmcInsumosEncontrados0: with default state.
	 *		.id : svwBuscarInsumoSM:smcInsumosEncontrados:_0
	 * 		.type : checkbox
	 * 		.value : 0
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarInsumoSM:smcInsumosEncontrados
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarInsumoSMSmcI() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarInsumoSMSmcI"));
	}
	/**
	 * svwBuscarInsumoSMSmcInsumosEncontrados0: with specific test context and state.
	 *		.id : svwBuscarInsumoSM:smcInsumosEncontrados:_0
	 * 		.type : checkbox
	 * 		.value : 0
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarInsumoSM:smcInsumosEncontrados
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarInsumoSMSmcI(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarInsumoSMSmcI"), anchor, flags);
	}
	
	/**
	 * BienvenidASIGFE: with default state.
	 *		.title : Bienvenid@ a SIGFE
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 */
	protected DocumentTestObject document_bienvenidASIGFE() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_bienvenidASIGFE"));
	}
	/**
	 * BienvenidASIGFE: with specific test context and state.
	 *		.title : Bienvenid@ a SIGFE
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 */
	protected DocumentTestObject document_bienvenidASIGFE(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_bienvenidASIGFE"), anchor, flags);
	}
	
	/**
	 * idPgTplFrmRRP: with default state.
	 *		.id : idPgTpl:frmRRP
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : idPgTpl:frmRRP
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_idPgTplFrmRRP() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_idPgTplFrmRRP"));
	}
	/**
	 * idPgTplFrmRRP: with specific test context and state.
	 *		.id : idPgTpl:frmRRP
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : idPgTpl:frmRRP
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_idPgTplFrmRRP(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_idPgTplFrmRRP"), anchor, flags);
	}
	
	/**
	 * idDocPrincipal: with default state.
	 *		.id : idDocPrincipal
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idDocPrincipal() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipal"));
	}
	/**
	 * idDocPrincipal: with specific test context and state.
	 *		.id : idDocPrincipal
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idDocPrincipal(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipal"), anchor, flags);
	}
	
	/**
	 * idPgTplCbsCrearDetalleIdPnBrdLyBotonSecundario: with default state.
	 *		.id : idPgTpl:cbsCrearDetalle:idPnBrdLyBotonSecundario
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplCbsCrearDetalleIdP() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplCbsCrearDetalleIdP"));
	}
	/**
	 * idPgTplCbsCrearDetalleIdPnBrdLyBotonSecundario: with specific test context and state.
	 *		.id : idPgTpl:cbsCrearDetalle:idPnBrdLyBotonSecundario
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplCbsCrearDetalleIdP(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplCbsCrearDetalleIdP"), anchor, flags);
	}
	
	/**
	 * idPgTplContenedorBotonSecundario: with default state.
	 *		.id : idPgTpl:contenedorBotonSecundario
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplContenedorBotonSec() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplContenedorBotonSec"));
	}
	/**
	 * idPgTplContenedorBotonSecundario: with specific test context and state.
	 *		.id : idPgTpl:contenedorBotonSecundario
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplContenedorBotonSec(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplContenedorBotonSec"), anchor, flags);
	}
	
	/**
	 * idPgTplCrearDesplegarDetalleActividad: with default state.
	 *		.id : idPgTpl:crearDesplegarDetalleActividad
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_idPgTplCrearDesplegarDeta() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplCrearDesplegarDeta"));
	}
	/**
	 * idPgTplCrearDesplegarDetalleActividad: with specific test context and state.
	 *		.id : idPgTpl:crearDesplegarDetalleActividad
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_idPgTplCrearDesplegarDeta(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplCrearDesplegarDeta"), anchor, flags);
	}
	
	/**
	 * idPgTplGroupLayoutMenu: with default state.
	 *		.id : idPgTpl:groupLayoutMenu
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplGroupLayoutMenu() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplGroupLayoutMenu"));
	}
	/**
	 * idPgTplGroupLayoutMenu: with specific test context and state.
	 *		.id : idPgTpl:groupLayoutMenu
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplGroupLayoutMenu(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplGroupLayoutMenu"), anchor, flags);
	}
	
	/**
	 * idPgTplIdPaBoLyContenidoPrincipal: with default state.
	 *		.id : idPgTpl:idPaBoLyContenidoPrincipal
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_idPgTplIdPaBoLyContenidoP() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplIdPaBoLyContenidoP"));
	}
	/**
	 * idPgTplIdPaBoLyContenidoPrincipal: with specific test context and state.
	 *		.id : idPgTpl:idPaBoLyContenidoPrincipal
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_idPgTplIdPaBoLyContenidoP(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplIdPaBoLyContenidoP"), anchor, flags);
	}
	
	/**
	 * idPgTplItTpoDdaContent: with default state.
	 *		.id : idPgTpl:itTpoDda::content
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplItTpoDdaContent() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplItTpoDdaContent"));
	}
	/**
	 * idPgTplItTpoDdaContent: with specific test context and state.
	 *		.id : idPgTpl:itTpoDda::content
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplItTpoDdaContent(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplItTpoDdaContent"), anchor, flags);
	}
	
	/**
	 * idPgTplPblContenedorPrincipal: with default state.
	 *		.id : idPgTpl:pblContenedorPrincipal
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplPblContenedorPrinc() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplPblContenedorPrinc"));
	}
	/**
	 * idPgTplPblContenedorPrincipal: with specific test context and state.
	 *		.id : idPgTpl:pblContenedorPrincipal
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplPblContenedorPrinc(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplPblContenedorPrinc"), anchor, flags);
	}
	
	/**
	 * idPgTplPblContenidoPpal: with default state.
	 *		.id : idPgTpl:pblContenidoPpal
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplPblContenidoPpal() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplPblContenidoPpal"));
	}
	/**
	 * idPgTplPblContenidoPpal: with specific test context and state.
	 *		.id : idPgTpl:pblContenidoPpal
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplPblContenidoPpal(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplPblContenidoPpal"), anchor, flags);
	}
	
	/**
	 * idPgTplPblRegistroCompletoRequerimiento: with default state.
	 *		.id : idPgTpl:pblRegistroCompletoRequerimiento
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_idPgTplPblRegistroComplet() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplPblRegistroComplet"));
	}
	/**
	 * idPgTplPblRegistroCompletoRequerimiento: with specific test context and state.
	 *		.id : idPgTpl:pblRegistroCompletoRequerimiento
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_idPgTplPblRegistroComplet(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplPblRegistroComplet"), anchor, flags);
	}
	
	/**
	 * ProgramaInserciónYAtracción: with default state.
	 *		.id : 
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_programaInserciónYAtracc() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_programaInserciónYAtracc"));
	}
	/**
	 * ProgramaInserciónYAtracción: with specific test context and state.
	 *		.id : 
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_programaInserciónYAtracc(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_programaInserciónYAtracc"), anchor, flags);
	}
	
	/**
	 * ProgramaInserciónYAtracción: with default state.
	 *		.id : 
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_programaInserciónYAtracc2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_programaInserciónYAtracc2"));
	}
	/**
	 * ProgramaInserciónYAtracción: with specific test context and state.
	 *		.id : 
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_programaInserciónYAtracc2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_programaInserciónYAtracc2"), anchor, flags);
	}
	
	/**
	 * idPgTplCmdLnkGuardarBorradorInferior: with default state.
	 *		.text : Guardar Digitado
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:cmdLnkGuardarBorradorInferior
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_idPgTplCmdLnkGuardarBorra() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplCmdLnkGuardarBorra"));
	}
	/**
	 * idPgTplCmdLnkGuardarBorradorInferior: with specific test context and state.
	 *		.text : Guardar Digitado
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:cmdLnkGuardarBorradorInferior
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_idPgTplCmdLnkGuardarBorra(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplCmdLnkGuardarBorra"), anchor, flags);
	}
	
	/**
	 * idPgTplIdLinkBandeja: with default state.
	 *		.text : Ir a Bandeja de Entrada
	 * 		.id : idPgTpl:idLinkBandeja
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=15ju5k6a9m_14&_afrL ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplIdLinkBandeja() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplIdLinkBandeja"));
	}
	/**
	 * idPgTplIdLinkBandeja: with specific test context and state.
	 *		.text : Ir a Bandeja de Entrada
	 * 		.id : idPgTpl:idLinkBandeja
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=15ju5k6a9m_14&_afrL ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplIdLinkBandeja(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplIdLinkBandeja"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrps0Cci1Cl2: with default state.
	 *		.text : Agregar Insumo
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:itAgrps:0:cci1:cl2
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps0Cci1Cl2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps0Cci1Cl2"));
	}
	/**
	 * idPgTplItAgrps0Cci1Cl2: with specific test context and state.
	 *		.text : Agregar Insumo
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:itAgrps:0:cci1:cl2
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps0Cci1Cl2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps0Cci1Cl2"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrps0Cci1ClkAddConc: with default state.
	 *		.text : Agregar Concepto Presupuestario
	 * 		.id : idPgTpl:itAgrps:0:cci1:clkAddConc
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps0Cci1ClkAdd() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps0Cci1ClkAdd"));
	}
	/**
	 * idPgTplItAgrps0Cci1ClkAddConc: with specific test context and state.
	 *		.text : Agregar Concepto Presupuestario
	 * 		.id : idPgTpl:itAgrps:0:cci1:clkAddConc
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps0Cci1ClkAdd(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps0Cci1ClkAdd"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrps1Cci1Cl2: with default state.
	 *		.text : Agregar Insumo
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:itAgrps:1:cci1:cl2
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps1Cci1Cl2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps1Cci1Cl2"));
	}
	/**
	 * idPgTplItAgrps1Cci1Cl2: with specific test context and state.
	 *		.text : Agregar Insumo
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:itAgrps:1:cci1:cl2
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps1Cci1Cl2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps1Cci1Cl2"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrps1Cci1ClkAddConc: with default state.
	 *		.text : Agregar Concepto Presupuestario
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:itAgrps:1:cci1:clkAddConc
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps1Cci1ClkAdd() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps1Cci1ClkAdd"));
	}
	/**
	 * idPgTplItAgrps1Cci1ClkAddConc: with specific test context and state.
	 *		.text : Agregar Concepto Presupuestario
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:itAgrps:1:cci1:clkAddConc
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps1Cci1ClkAdd(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps1Cci1ClkAdd"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrps2Cci1Cl2: with default state.
	 *		.text : Agregar Insumo
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:itAgrps:2:cci1:cl2
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps2Cci1Cl2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps2Cci1Cl2"));
	}
	/**
	 * idPgTplItAgrps2Cci1Cl2: with specific test context and state.
	 *		.text : Agregar Insumo
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:itAgrps:2:cci1:cl2
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps2Cci1Cl2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps2Cci1Cl2"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrps2Cci1ClkAddConc: with default state.
	 *		.text : Agregar Concepto Presupuestario
	 * 		.id : idPgTpl:itAgrps:2:cci1:clkAddConc
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps2Cci1ClkAdd() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps2Cci1ClkAdd"));
	}
	/**
	 * idPgTplItAgrps2Cci1ClkAddConc: with specific test context and state.
	 *		.text : Agregar Concepto Presupuestario
	 * 		.id : idPgTpl:itAgrps:2:cci1:clkAddConc
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps2Cci1ClkAdd(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps2Cci1ClkAdd"), anchor, flags);
	}
	
	/**
	 * idTmpBIdTbRqB0LinkVisualizar: with default state.
	 *		.text : Visualizar
	 * 		.id : idTmpB:idTbRqB:0:linkVisualizar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-buscar/busquedaRequeri ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_idTmpBIdTbRqB0LinkVisuali() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idTmpBIdTbRqB0LinkVisuali"));
	}
	/**
	 * idTmpBIdTbRqB0LinkVisualizar: with specific test context and state.
	 *		.text : Visualizar
	 * 		.id : idTmpB:idTbRqB:0:linkVisualizar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-buscar/busquedaRequeri ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_idTmpBIdTbRqB0LinkVisuali(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idTmpBIdTbRqB0LinkVisuali"), anchor, flags);
	}
	
	/**
	 * IrABienvenida: with default state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/bandeja?_adf.ctrl-state=15ju5k6a9m_14&_afrLoop ...
	 * 		.id : idPgTpl:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida"));
	}
	/**
	 * IrABienvenida: with specific test context and state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/bandeja?_adf.ctrl-state=15ju5k6a9m_14&_afrLoop ...
	 * 		.id : idPgTpl:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida"), anchor, flags);
	}
	
	/**
	 * IrABienvenida: with default state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-buscar/busquedaRequeri ...
	 * 		.id : idTmpB:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida2"));
	}
	/**
	 * IrABienvenida: with specific test context and state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-buscar/busquedaRequeri ...
	 * 		.id : idTmpB:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida2"), anchor, flags);
	}
	
	/**
	 * Requerimiento: with default state.
	 *		.text : Requerimiento
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenidaInicio?_afrWindowMode=0&_adf.no-new- ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_requerimiento() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_requerimiento"));
	}
	/**
	 * Requerimiento: with specific test context and state.
	 *		.text : Requerimiento
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenidaInicio?_afrWindowMode=0&_adf.no-new- ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_requerimiento(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_requerimiento"), anchor, flags);
	}
	
	/**
	 * Requerimiento: with default state.
	 *		.text : Requerimiento
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=15ju5k6a9m_14&_afrL ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_requerimiento2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_requerimiento2"));
	}
	/**
	 * Requerimiento: with specific test context and state.
	 *		.text : Requerimiento
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=15ju5k6a9m_14&_afrL ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_requerimiento2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_requerimiento2"), anchor, flags);
	}
	
	/**
	 * Seleccione: with default state.
	 *		.text : Seleccione... Ley de Presupuestos Fondos no afectos a Ley
	 * 		.id : idPgTpl:idSeOnChTipoDemanda::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeOnChTipoDemanda
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione"));
	}
	/**
	 * Seleccione: with specific test context and state.
	 *		.text : Seleccione... Ley de Presupuestos Fondos no afectos a Ley
	 * 		.id : idPgTpl:idSeOnChTipoDemanda::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeOnChTipoDemanda
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione"), anchor, flags);
	}
	
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC11SbrACCCat1: with default state.
	 *		.id : svwCombinacCatalogos:trACC1:1:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:1:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb"));
	}
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC11SbrACCCat1: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC1:1:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:1:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb"), anchor, flags);
	}
	
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC10SbrACCCat1: with default state.
	 *		.id : svwCombinacCatalogos:trACC1:0:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:0:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb2() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb2"));
	}
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC10SbrACCCat1: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC1:0:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:0:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb2(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb2"), anchor, flags);
	}
	
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC11SbrACCCat1: with default state.
	 *		.id : svwCombinacCatalogos:trACC1:1:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:1:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb3() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb3"));
	}
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC11SbrACCCat1: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC1:1:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:1:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb3(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb3"), anchor, flags);
	}
	
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC12SbrACCCat1: with default state.
	 *		.id : svwCombinacCatalogos:trACC1:2:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:2:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb4() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb4"));
	}
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC12SbrACCCat1: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC1:2:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:2:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb4(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb4"), anchor, flags);
	}
	
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC17SbrACCCat1: with default state.
	 *		.id : svwCombinacCatalogos:trACC1:7:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:7:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb5() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb5"));
	}
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC17SbrACCCat1: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC1:7:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:7:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb5(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb5"), anchor, flags);
	}
	
	/**
	 * rbCatalogo2svwCombinacCatalogosTrACC20SbrACCCat2: with default state.
	 *		.id : svwCombinacCatalogos:trACC2:0:sbrACCCat2::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC2:0:sbrACCCat2
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo2
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo2svwComb() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo2svwComb"));
	}
	/**
	 * rbCatalogo2svwCombinacCatalogosTrACC20SbrACCCat2: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC2:0:sbrACCCat2::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC2:0:sbrACCCat2
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo2
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo2svwComb(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo2svwComb"), anchor, flags);
	}
	
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre1SbrACCCat3: with default state.
	 *		.id : svwCombinacCatalogos:treeTre:1:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:1:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb"));
	}
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre1SbrACCCat3: with specific test context and state.
	 *		.id : svwCombinacCatalogos:treeTre:1:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:1:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb"), anchor, flags);
	}
	
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre0SbrACCCat3: with default state.
	 *		.id : svwCombinacCatalogos:treeTre:0:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:0:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb2() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb2"));
	}
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre0SbrACCCat3: with specific test context and state.
	 *		.id : svwCombinacCatalogos:treeTre:0:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:0:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb2(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb2"), anchor, flags);
	}
	
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre7SbrACCCat3: with default state.
	 *		.id : svwCombinacCatalogos:treeTre:7:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:7:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb3() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb3"));
	}
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre7SbrACCCat3: with specific test context and state.
	 *		.id : svwCombinacCatalogos:treeTre:7:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:7:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb3(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb3"), anchor, flags);
	}
	
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre1SbrACCCat3: with default state.
	 *		.id : svwCombinacCatalogos:treeTre:1:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:1:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb4() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb4"));
	}
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre1SbrACCCat3: with specific test context and state.
	 *		.id : svwCombinacCatalogos:treeTre:1:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:1:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb4(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb4"), anchor, flags);
	}
	
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre2SbrACCCat3: with default state.
	 *		.id : svwCombinacCatalogos:treeTre:2:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:2:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb5() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb5"));
	}
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre2SbrACCCat3: with specific test context and state.
	 *		.id : svwCombinacCatalogos:treeTre:2:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:2:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb5(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb5"), anchor, flags);
	}
	
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre8SbrACCCat3: with default state.
	 *		.id : svwCombinacCatalogos:treeTre:8:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:8:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb6() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb6"));
	}
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre8SbrACCCat3: with specific test context and state.
	 *		.id : svwCombinacCatalogos:treeTre:8:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:8:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb6(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb6"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_2"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_2"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id11Menu: with default state.
	 *		.id : idPgTpl:j_id11::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id11Menu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id11Menu"));
	}
	/**
	 * idPgTplJ_id11Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id11::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id11Menu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id11Menu"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id11Menu: with default state.
	 *		.id : idPgTpl:j_id11::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id11Menu2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id11Menu2"));
	}
	/**
	 * idPgTplJ_id11Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id11::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id11Menu2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id11Menu2"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id22Menu: with default state.
	 *		.id : idPgTpl:j_id22::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id22Menu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id22Menu"));
	}
	/**
	 * idPgTplJ_id22Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id22::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id22Menu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id22Menu"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id23Menu: with default state.
	 *		.id : idPgTpl:j_id23::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id23Menu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id23Menu"));
	}
	/**
	 * idPgTplJ_id23Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id23::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id23Menu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id23Menu"), anchor, flags);
	}
	
	/**
	 * idPgTplPnlGrLyCrearDetalleActividad: with default state.
	 *		.id : idPgTpl:pnlGrLyCrearDetalleActividad
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplPnlGrLyCrearDetal() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplPnlGrLyCrearDetal"));
	}
	/**
	 * idPgTplPnlGrLyCrearDetalleActividad: with specific test context and state.
	 *		.id : idPgTpl:pnlGrLyCrearDetalleActividad
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplPnlGrLyCrearDetal(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplPnlGrLyCrearDetal"), anchor, flags);
	}
	
	/**
	 * pt2ContenedorMsj: with default state.
	 *		.id : pt2:contenedorMsj
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_pt2ContenedorMsj() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_pt2ContenedorMsj"));
	}
	/**
	 * pt2ContenedorMsj: with specific test context and state.
	 *		.id : pt2:contenedorMsj
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_pt2ContenedorMsj(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_pt2ContenedorMsj"), anchor, flags);
	}
	
	/**
	 * idPgTplDescripcion: with default state.
	 *		.id : idPgTpl:descripcion::content
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : idPgTpl:descripcion
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplDescripcion() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplDescripcion"));
	}
	/**
	 * idPgTplDescripcion: with specific test context and state.
	 *		.id : idPgTpl:descripcion::content
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : idPgTpl:descripcion
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplDescripcion(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplDescripcion"), anchor, flags);
	}
	
	/**
	 * idPgTplTitulo: with default state.
	 *		.id : idPgTpl:titulo::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:titulo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplTitulo() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplTitulo"));
	}
	/**
	 * idPgTplTitulo: with specific test context and state.
	 *		.id : idPgTpl:titulo::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:titulo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplTitulo(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplTitulo"), anchor, flags);
	}
	
	/**
	 * idTmpBIdTransaccional: with default state.
	 *		.id : idTmpB:idTransaccional::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idTmpB:idTransaccional
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idTmpBIdTransaccional() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idTmpBIdTransaccional"));
	}
	/**
	 * idTmpBIdTransaccional: with specific test context and state.
	 *		.id : idTmpB:idTransaccional::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idTmpB:idTransaccional
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idTmpBIdTransaccional(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idTmpBIdTransaccional"), anchor, flags);
	}
	
	/**
	 * j_password: with default state.
	 *		.id : 
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : j_password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_password() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_password"));
	}
	/**
	 * j_password: with specific test context and state.
	 *		.id : 
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : j_password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_password(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_password"), anchor, flags);
	}
	
	/**
	 * j_username: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : j_username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_username() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_username"));
	}
	/**
	 * j_username: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : j_username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_username(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_username"), anchor, flags);
	}
	
	/**
	 * svwAgregarConceptoPresPopUpTAddCP0Valor: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:0:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:0:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop"));
	}
	/**
	 * svwAgregarConceptoPresPopUpTAddCP0Valor: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:0:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:0:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop"), anchor, flags);
	}
	
	/**
	 * svwAgregarInsumoPopUpTblIns0TotalTabla: with default state.
	 *		.id : svwAgregarInsumoPopUp:tblIns:0:totalTabla::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarInsumoPopUp:tblIns:0:totalTabla
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarInsumoPopUpTblI() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarInsumoPopUpTblI"));
	}
	/**
	 * svwAgregarInsumoPopUpTblIns0TotalTabla: with specific test context and state.
	 *		.id : svwAgregarInsumoPopUp:tblIns:0:totalTabla::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarInsumoPopUp:tblIns:0:totalTabla
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarInsumoPopUpTblI(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarInsumoPopUpTblI"), anchor, flags);
	}
	
	/**
	 * svwBuscarConceptoSMIntxCodigoCpt: with default state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwBuscarConceptoSMIntxCo() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwBuscarConceptoSMIntxCo"));
	}
	/**
	 * svwBuscarConceptoSMIntxCodigoCpt: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwBuscarConceptoSMIntxCo(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwBuscarConceptoSMIntxCo"), anchor, flags);
	}
	
	/**
	 * svwBuscarInsumoSMIdInteCodigo: with default state.
	 *		.id : svwBuscarInsumoSM:idInteCodigo::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarInsumoSM:idInteCodigo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwBuscarInsumoSMIdInteCo() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwBuscarInsumoSMIdInteCo"));
	}
	/**
	 * svwBuscarInsumoSMIdInteCodigo: with specific test context and state.
	 *		.id : svwBuscarInsumoSM:idInteCodigo::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarInsumoSM:idInteCodigo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwBuscarInsumoSMIdInteCo(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwBuscarInsumoSMIdInteCo"), anchor, flags);
	}
	
	

	protected RP_GENERICO_01Helper()
	{
		setScriptName("Script.RP_GENERICO_01");
	}
	
}

