// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Script;
import LIB.Libreria;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>TEF_GENERICO_07</b><br>
 * Generated     : <b>2014/04/09 10:08:57</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 <br>
 * 
 * @since  abril 09, 2014
 * @author cpena
 */
public abstract class TEF_GENERICO_07Helper extends LIB.Libreria
{
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit2"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit2"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit3"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit3"), anchor, flags);
	}
	
	/**
	 * Buscarsubmit: with default state.
	 *		.id : idPgTpl:siCBBuscar:idCmbIrBuscar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit"));
	}
	/**
	 * Buscarsubmit: with specific test context and state.
	 *		.id : idPgTpl:siCBBuscar:idCmbIrBuscar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit"), anchor, flags);
	}
	
	/**
	 * Buscarsubmit: with default state.
	 *		.id : idPgTpl:siCBBuscar:idCmbIrBuscar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit2"));
	}
	/**
	 * Buscarsubmit: with specific test context and state.
	 *		.id : idPgTpl:siCBBuscar:idCmbIrBuscar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit2"), anchor, flags);
	}
	
	/**
	 * Emitirsubmit: with default state.
	 *		.id : idPgTpl:componenteBotonBuscarPE:idCmbIrBuscarProgramaPE
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_emitirsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_emitirsubmit"));
	}
	/**
	 * Emitirsubmit: with specific test context and state.
	 *		.id : idPgTpl:componenteBotonBuscarPE:idCmbIrBuscarProgramaPE
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_emitirsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_emitirsubmit"), anchor, flags);
	}
	
	/**
	 * Enviarsubmit: with default state.
	 *		.id : pt2:componenteBotonDB:idCmbDB
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_enviarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_enviarsubmit"));
	}
	/**
	 * Enviarsubmit: with specific test context and state.
	 *		.id : pt2:componenteBotonDB:idCmbDB
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_enviarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_enviarsubmit"), anchor, flags);
	}
	
	/**
	 * Generarsubmit: with default state.
	 *		.id : idPgTpl:componenteBotonDB:idCmbDB
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_generarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_generarsubmit"));
	}
	/**
	 * Generarsubmit: with specific test context and state.
	 *		.id : idPgTpl:componenteBotonDB:idCmbDB
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_generarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_generarsubmit"), anchor, flags);
	}
	
	/**
	 * IrALaBandejaDeEntradasubmit: with default state.
	 *		.id : pt2:idComponenteBotonRepetir:botonRepetir
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_irALaBandejaDeEntradasu() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_irALaBandejaDeEntradasu"));
	}
	/**
	 * IrALaBandejaDeEntradasubmit: with specific test context and state.
	 *		.id : pt2:idComponenteBotonRepetir:botonRepetir
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_irALaBandejaDeEntradasu(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_irALaBandejaDeEntradasu"), anchor, flags);
	}
	
	/**
	 * idDocPrincipalMsgDlg_ttxt: with default state.
	 *		.id : idDocPrincipal::msgDlg::_ttxt
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_idDocPrincipalMsgDlg_ttxt() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipalMsgDlg_ttxt"));
	}
	/**
	 * idDocPrincipalMsgDlg_ttxt: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::_ttxt
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_idDocPrincipalMsgDlg_ttxt(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipalMsgDlg_ttxt"), anchor, flags);
	}
	
	/**
	 * AmpliarMostrar: with default state.
	 *		.alt : Ampliar Mostrar
	 * 		.id : 
	 * 		.src : http://192.168.203.10/sigfe/afr/disclosure_collapsed.png
	 * 		.title : Ampliar Mostrar
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_ampliarMostrar() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_ampliarMostrar"));
	}
	/**
	 * AmpliarMostrar: with specific test context and state.
	 *		.alt : Ampliar Mostrar
	 * 		.id : 
	 * 		.src : http://192.168.203.10/sigfe/afr/disclosure_collapsed.png
	 * 		.title : Ampliar Mostrar
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_ampliarMostrar(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_ampliarMostrar"), anchor, flags);
	}
	
	/**
	 * FuncionalidadesComplementarias: with default state.
	 *		.text : Funcionalidades Complementarias
	 * 		.id : 
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenidaInicio?_adf.no-new-window-redirect=t ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_funcionalidadesComplement() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_funcionalidadesComplement"));
	}
	/**
	 * FuncionalidadesComplementarias: with specific test context and state.
	 *		.text : Funcionalidades Complementarias
	 * 		.id : 
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenidaInicio?_adf.no-new-window-redirect=t ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_funcionalidadesComplement(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_funcionalidadesComplement"), anchor, flags);
	}
	
	/**
	 * FuncionalidadesComplementarias: with default state.
	 *		.text : Funcionalidades Complementarias
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=gqpy65iwg_14&_afrLo ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_funcionalidadesComplement2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_funcionalidadesComplement2"));
	}
	/**
	 * FuncionalidadesComplementarias: with specific test context and state.
	 *		.text : Funcionalidades Complementarias
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=gqpy65iwg_14&_afrLo ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_funcionalidadesComplement2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_funcionalidadesComplement2"), anchor, flags);
	}
	
	/**
	 * idPgTplT10IdCmliLimpiarPE: with default state.
	 *		.text : 6
	 * 		.id : idPgTpl:t1:0:idCmliLimpiarPE
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-fc-transferenciaEF-menu/cuadroContro ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplT10IdCmliLimpiarPE() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplT10IdCmliLimpiarPE"));
	}
	/**
	 * idPgTplT10IdCmliLimpiarPE: with specific test context and state.
	 *		.text : 6
	 * 		.id : idPgTpl:t1:0:idCmliLimpiarPE
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-fc-transferenciaEF-menu/cuadroContro ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplT10IdCmliLimpiarPE(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplT10IdCmliLimpiarPE"), anchor, flags);
	}
	
	/**
	 * IrABienvenida: with default state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/bandeja?_adf.ctrl-state=gqpy65iwg_14&_afrLoop= ...
	 * 		.id : idPgTpl:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida"));
	}
	/**
	 * IrABienvenida: with specific test context and state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/bandeja?_adf.ctrl-state=gqpy65iwg_14&_afrLoop= ...
	 * 		.id : idPgTpl:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida"), anchor, flags);
	}
	
	/**
	 * IrABienvenida: with default state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-fc-emisionCheques/emisionCh?_adf.ctr ...
	 * 		.id : idPgTpl:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida2"));
	}
	/**
	 * IrABienvenida: with specific test context and state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-fc-emisionCheques/emisionCh?_adf.ctr ...
	 * 		.id : idPgTpl:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida2"), anchor, flags);
	}
	
	/**
	 * IrABienvenida: with default state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-fc-emisionCheques/emisionCh?_adf.ctr ...
	 * 		.id : pt2:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida3"));
	}
	/**
	 * IrABienvenida: with specific test context and state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-fc-emisionCheques/emisionCh?_adf.ctr ...
	 * 		.id : pt2:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida3"), anchor, flags);
	}
	
	/**
	 * ChequeAutomático: with default state.
	 *		.text : Seleccione... Cheque Automático Cheque Manual
	 * 		.id : idPgTpl:idSeonchMedioPago::content
	 * 		.title : Cheque Automático
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchMedioPago
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_chequeAutomático() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_chequeAutomático"));
	}
	/**
	 * ChequeAutomático: with specific test context and state.
	 *		.text : Seleccione... Cheque Automático Cheque Manual
	 * 		.id : idPgTpl:idSeonchMedioPago::content
	 * 		.title : Cheque Automático
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchMedioPago
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_chequeAutomático(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_chequeAutomático"), anchor, flags);
	}
	
	/**
	 * Seleccione: with default state.
	 *		.text : Seleccione... BANCO ESTADO INTERMEDIACION
	 * 		.id : idPgTpl:idSeonchBanco::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchBanco
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione"));
	}
	/**
	 * Seleccione: with specific test context and state.
	 *		.text : Seleccione... BANCO ESTADO INTERMEDIACION
	 * 		.id : idPgTpl:idSeonchBanco::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchBanco
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione"), anchor, flags);
	}
	
	/**
	 * Seleccione: with default state.
	 *		.text : Seleccione... 00009002189 00009004580 00009001531 00009001280 00009000488 000090 ...
	 * 		.id : idPgTpl:idSeonchCuentaBancaria::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchCuentaBancaria
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione2() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione2"));
	}
	/**
	 * Seleccione: with specific test context and state.
	 *		.text : Seleccione... 00009002189 00009004580 00009001531 00009001280 00009000488 000090 ...
	 * 		.id : idPgTpl:idSeonchCuentaBancaria::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchCuentaBancaria
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione2(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione2"), anchor, flags);
	}
	
	/**
	 * Seleccione: with default state.
	 *		.text : Seleccione... CONVENIO DE PROVEEDORES
	 * 		.id : pt2:iterTef:0:selectorConvenio::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : pt2:iterTef:0:selectorConvenio
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione3() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione3"));
	}
	/**
	 * Seleccione: with specific test context and state.
	 *		.text : Seleccione... CONVENIO DE PROVEEDORES
	 * 		.id : pt2:iterTef:0:selectorConvenio::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : pt2:iterTef:0:selectorConvenio
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione3(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione3"), anchor, flags);
	}
	
	/**
	 * Seleccione: with default state.
	 *		.text : Seleccione... BANCO ESTADO INTERMEDIACION
	 * 		.id : idPgTpl:idSeonchBanco::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchBanco
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_seleccione4() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione4"));
	}
	/**
	 * Seleccione: with specific test context and state.
	 *		.text : Seleccione... BANCO ESTADO INTERMEDIACION
	 * 		.id : idPgTpl:idSeonchBanco::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchBanco
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_seleccione4(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione4"), anchor, flags);
	}
	
	/**
	 * Seleccione: with default state.
	 *		.text : Seleccione... 00009002189 00009004580 00009001531 00009001280 00009000488 000090 ...
	 * 		.id : idPgTpl:idSeonchCuentaBancaria::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchCuentaBancaria
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_seleccione5() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione5"));
	}
	/**
	 * Seleccione: with specific test context and state.
	 *		.text : Seleccione... 00009002189 00009004580 00009001531 00009001280 00009000488 000090 ...
	 * 		.id : idPgTpl:idSeonchCuentaBancaria::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchCuentaBancaria
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_seleccione5(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione5"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id110Menu: with default state.
	 *		.id : idPgTpl:j_id110::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id110Menu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id110Menu"));
	}
	/**
	 * idPgTplJ_id110Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id110::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id110Menu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id110Menu"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id110Menu: with default state.
	 *		.id : idPgTpl:j_id110::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id110Menu2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id110Menu2"));
	}
	/**
	 * idPgTplJ_id110Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id110::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id110Menu2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id110Menu2"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id117Menu: with default state.
	 *		.id : idPgTpl:j_id117::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id117Menu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id117Menu"));
	}
	/**
	 * idPgTplJ_id117Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id117::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id117Menu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id117Menu"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id120Menu: with default state.
	 *		.id : idPgTpl:j_id120::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id120Menu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id120Menu"));
	}
	/**
	 * idPgTplJ_id120Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id120::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id120Menu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id120Menu"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id120Menu: with default state.
	 *		.id : idPgTpl:j_id120::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id120Menu2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id120Menu2"));
	}
	/**
	 * idPgTplJ_id120Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id120::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id120Menu2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id120Menu2"), anchor, flags);
	}
	
	

	protected TEF_GENERICO_07Helper()
	{
		setScriptName("Script.TEF_GENERICO_07");
	}
	
}

