// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Modulos.Requerimiento;
import Librerias.Funciones_Globales;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>RP_Multiple_Gastos_Moneda_Nacional_Generar</b><br>
 * Generated     : <b>2014/08/27 16:16:19</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 <br>
 * 
 * @since  agosto 27, 2014
 * @author cpena
 */
public abstract class RP_Multiple_Gastos_Moneda_Nacional_GenerarHelper extends Librerias.Funciones_Globales
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox 17.0
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox 17.0
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : svwCombinacCatalogos:btnAceptarComb
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : svwCombinacCatalogos:btnAceptarComb
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:btnAceptarIns
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit2"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:btnAceptarIns
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit2"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:btnAceptarIns
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit3"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:btnAceptarIns
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit3"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:btnAceptarIns
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit4() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit4"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:btnAceptarIns
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit4(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit4"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit5() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit5"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit5(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit5"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit6() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit6"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit6(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit6"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit7() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit7"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit7(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit7"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit8() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit8"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit8(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit8"), anchor, flags);
	}
	
	/**
	 * AgregarCombinaciónsubmit: with default state.
	 *		.id : svwCombinacCatalogos:idCpteBtnSecAgregar:cmbACCAgregar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_agregarCombinaciónsubmi() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_agregarCombinaciónsubmi"));
	}
	/**
	 * AgregarCombinaciónsubmit: with specific test context and state.
	 *		.id : svwCombinacCatalogos:idCpteBtnSecAgregar:cmbACCAgregar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_agregarCombinaciónsubmi(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_agregarCombinaciónsubmi"), anchor, flags);
	}
	
	/**
	 * Agregarsubmit: with default state.
	 *		.id : svwBuscarConceptoSM:cbs1:cb2
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_agregarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_agregarsubmit"));
	}
	/**
	 * Agregarsubmit: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:cbs1:cb2
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_agregarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_agregarsubmit"), anchor, flags);
	}
	
	/**
	 * Agregarsubmit: with default state.
	 *		.id : svwBuscarConceptoSM:cbs1:cb2
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_agregarsubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_agregarsubmit2"));
	}
	/**
	 * Agregarsubmit: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:cbs1:cb2
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_agregarsubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_agregarsubmit2"), anchor, flags);
	}
	
	/**
	 * Agregarsubmit: with default state.
	 *		.id : svwBuscarConceptoSM:cbs1:cb2
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_agregarsubmit3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_agregarsubmit3"));
	}
	/**
	 * Agregarsubmit: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:cbs1:cb2
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_agregarsubmit3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_agregarsubmit3"), anchor, flags);
	}
	
	/**
	 * Buscarsubmit: with default state.
	 *		.id : svwBuscarConceptoSM:cbp1:cb1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit"));
	}
	/**
	 * Buscarsubmit: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:cbp1:cb1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit"), anchor, flags);
	}
	
	/**
	 * Buscarsubmit: with default state.
	 *		.id : svwBuscarConceptoSM:cbp1:cb1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit2"));
	}
	/**
	 * Buscarsubmit: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:cbp1:cb1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit2"), anchor, flags);
	}
	
	/**
	 * Buscarsubmit: with default state.
	 *		.id : svwBuscarConceptoSM:cbp1:cb1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit3"));
	}
	/**
	 * Buscarsubmit: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:cbp1:cb1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit3"), anchor, flags);
	}
	
	/**
	 * Cancelarsubmit: with default state.
	 *		.id : svwBuscarConceptoSM:idDialConBusq::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_cancelarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_cancelarsubmit"));
	}
	/**
	 * Cancelarsubmit: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:idDialConBusq::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_cancelarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_cancelarsubmit"), anchor, flags);
	}
	
	/**
	 * ConfirmarSelecciónsubmit: with default state.
	 *		.id : svwBuscarConceptoSM:comp_BotonConfSeleccion_1:botonConfSelec_1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi"));
	}
	/**
	 * ConfirmarSelecciónsubmit: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:comp_BotonConfSeleccion_1:botonConfSelec_1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi"), anchor, flags);
	}
	
	/**
	 * ConfirmarSelecciónsubmit: with default state.
	 *		.id : svwBuscarConceptoSM:comp_BotonConfSeleccion_1:botonConfSelec_1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi2"));
	}
	/**
	 * ConfirmarSelecciónsubmit: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:comp_BotonConfSeleccion_1:botonConfSelec_1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi2"), anchor, flags);
	}
	
	/**
	 * ConfirmarSelecciónsubmit: with default state.
	 *		.id : svwBuscarConceptoSM:comp_BotonConfSeleccion_1:botonConfSelec_1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi3"));
	}
	/**
	 * ConfirmarSelecciónsubmit: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:comp_BotonConfSeleccion_1:botonConfSelec_1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi3"), anchor, flags);
	}
	
	/**
	 * CrearDetallesubmit: with default state.
	 *		.id : idPgTpl:cbsCrearDetalle:claddct
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_crearDetallesubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_crearDetallesubmit"));
	}
	/**
	 * CrearDetallesubmit: with specific test context and state.
	 *		.id : idPgTpl:cbsCrearDetalle:claddct
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_crearDetallesubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_crearDetallesubmit"), anchor, flags);
	}
	
	/**
	 * Generarsubmit: with default state.
	 *		.id : idPgTpl:componenteBotonGenerarRequerimiento:botonGenerarRequerimiento
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_generarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_generarsubmit"));
	}
	/**
	 * Generarsubmit: with specific test context and state.
	 *		.id : idPgTpl:componenteBotonGenerarRequerimiento:botonGenerarRequerimiento
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_generarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_generarsubmit"), anchor, flags);
	}
	
	/**
	 * Ingresarsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Ingresar
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_ingresarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_ingresarsubmit"));
	}
	/**
	 * Ingresarsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Ingresar
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_ingresarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_ingresarsubmit"), anchor, flags);
	}
	
	/**
	 * TerminarLaTransacciónsubmit: with default state.
	 *		.id : pt2:idComponenteBoton:botonInicio
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_terminarLaTransacciónsu() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_terminarLaTransacciónsu"));
	}
	/**
	 * TerminarLaTransacciónsubmit: with specific test context and state.
	 *		.id : pt2:idComponenteBoton:botonInicio
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_terminarLaTransacciónsu(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_terminarLaTransacciónsu"), anchor, flags);
	}
	
	/**
	 * svwBuscarConceptoSMSmcConceptosEncontrados0: with default state.
	 *		.id : svwBuscarConceptoSM:smcConceptosEncontrados:_0
	 * 		.type : checkbox
	 * 		.value : 0
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarConceptoSM:smcConceptosEncontrados
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarConceptoSMSm() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarConceptoSMSm"));
	}
	/**
	 * svwBuscarConceptoSMSmcConceptosEncontrados0: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:smcConceptosEncontrados:_0
	 * 		.type : checkbox
	 * 		.value : 0
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarConceptoSM:smcConceptosEncontrados
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarConceptoSMSm(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarConceptoSMSm"), anchor, flags);
	}
	
	/**
	 * svwBuscarConceptoSMSmcConceptosEncontrados0: with default state.
	 *		.id : svwBuscarConceptoSM:smcConceptosEncontrados:_0
	 * 		.type : checkbox
	 * 		.value : 0
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarConceptoSM:smcConceptosEncontrados
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarConceptoSMSm2() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarConceptoSMSm2"));
	}
	/**
	 * svwBuscarConceptoSMSmcConceptosEncontrados0: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:smcConceptosEncontrados:_0
	 * 		.type : checkbox
	 * 		.value : 0
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarConceptoSM:smcConceptosEncontrados
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarConceptoSMSm2(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarConceptoSMSm2"), anchor, flags);
	}
	
	/**
	 * svwBuscarConceptoSMSmcConceptosEncontrados0: with default state.
	 *		.id : svwBuscarConceptoSM:smcConceptosEncontrados:_0
	 * 		.type : checkbox
	 * 		.value : 0
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarConceptoSM:smcConceptosEncontrados
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarConceptoSMSm3() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarConceptoSMSm3"));
	}
	/**
	 * svwBuscarConceptoSMSmcConceptosEncontrados0: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:smcConceptosEncontrados:_0
	 * 		.type : checkbox
	 * 		.value : 0
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarConceptoSM:smcConceptosEncontrados
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarConceptoSMSm3(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarConceptoSMSm3"), anchor, flags);
	}
	
	/**
	 * BienvenidASIGFE: with default state.
	 *		.title : Bienvenid@ a SIGFE
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 */
	protected DocumentTestObject document_bienvenidASIGFE() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_bienvenidASIGFE"));
	}
	/**
	 * BienvenidASIGFE: with specific test context and state.
	 *		.title : Bienvenid@ a SIGFE
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 */
	protected DocumentTestObject document_bienvenidASIGFE(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_bienvenidASIGFE"), anchor, flags);
	}
	
	/**
	 * idPgTplIdFormcambioArea: with default state.
	 *		.id : idPgTpl:idFormcambioArea
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : idPgTpl:idFormcambioArea
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_idPgTplIdFormcambioArea() 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_idPgTplIdFormcambioArea"));
	}
	/**
	 * idPgTplIdFormcambioArea: with specific test context and state.
	 *		.id : idPgTpl:idFormcambioArea
	 * 		.title : 
	 * 		.class : Html.FORM
	 * 		.name : idPgTpl:idFormcambioArea
	 * 		.classIndex : 0
	 */
	protected GuiTestObject form_idPgTplIdFormcambioArea(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("form_idPgTplIdFormcambioArea"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject htmlTable_ProgramaPres() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("htmlTable_ProgramaPres"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject htmlTable_ProgramaPres(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("htmlTable_ProgramaPres"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject htmlTable_Programas_Internos() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("htmlTable_Programas_Internos"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject htmlTable_Programas_Internos(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("htmlTable_Programas_Internos"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject htmlTable_UnidadesDemandantes() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("htmlTable_UnidadesDemandantes"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject htmlTable_UnidadesDemandantes(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("htmlTable_UnidadesDemandantes"), anchor, flags);
	}
	
	/**
	 * _1409000576469: with default state.
	 *		.id : 1409000576469
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html__1409000576469() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__1409000576469"));
	}
	/**
	 * _1409000576469: with specific test context and state.
	 *		.id : 1409000576469
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html__1409000576469(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__1409000576469"), anchor, flags);
	}
	
	/**
	 * _1409170069981: with default state.
	 *		.id : 1409170069981
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html__1409170069981() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__1409170069981"));
	}
	/**
	 * _1409170069981: with specific test context and state.
	 *		.id : 1409170069981
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html__1409170069981(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html__1409170069981"), anchor, flags);
	}
	
	/**
	 * __af_Z_window: with default state.
	 *		.id : __af_Z_window
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html___af_Z_window() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html___af_Z_window"));
	}
	/**
	 * __af_Z_window: with specific test context and state.
	 *		.id : __af_Z_window
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html___af_Z_window(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html___af_Z_window"), anchor, flags);
	}
	
	/**
	 * confirmarPopupPanelMensajeConfirmacion: with default state.
	 *		.id : confirmarPopup:panelMensajeConfirmacion
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 2
	 */
	protected GuiTestObject html_confirmarPopupPanelMensaj() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_confirmarPopupPanelMensaj"));
	}
	/**
	 * confirmarPopupPanelMensajeConfirmacion: with specific test context and state.
	 *		.id : confirmarPopup:panelMensajeConfirmacion
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 2
	 */
	protected GuiTestObject html_confirmarPopupPanelMensaj(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_confirmarPopupPanelMensaj"), anchor, flags);
	}
	
	/**
	 * confirmarPopupPanelMensajesConfirmarAccion: with default state.
	 *		.id : confirmarPopup:panelMensajesConfirmarAccion
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_confirmarPopupPanelMensaj2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_confirmarPopupPanelMensaj2"));
	}
	/**
	 * confirmarPopupPanelMensajesConfirmarAccion: with specific test context and state.
	 *		.id : confirmarPopup:panelMensajesConfirmarAccion
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_confirmarPopupPanelMensaj2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_confirmarPopupPanelMensaj2"), anchor, flags);
	}
	
	/**
	 * confirmarPopupPopupConfirmarAccionDialog: with default state.
	 *		.id : confirmarPopup:popupConfirmarAccionDialog
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_confirmarPopupPopupConfir() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_confirmarPopupPopupConfir"));
	}
	/**
	 * confirmarPopupPopupConfirmarAccionDialog: with specific test context and state.
	 *		.id : confirmarPopup:popupConfirmarAccionDialog
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_confirmarPopupPopupConfir(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_confirmarPopupPopupConfir"), anchor, flags);
	}
	
	/**
	 * confirmarPopupPopupConfirmarAccionContent: with default state.
	 *		.id : confirmarPopup:popupConfirmarAccion::content
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_confirmarPopupPopupConfir2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_confirmarPopupPopupConfir2"));
	}
	/**
	 * confirmarPopupPopupConfirmarAccionContent: with specific test context and state.
	 *		.id : confirmarPopup:popupConfirmarAccion::content
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_confirmarPopupPopupConfir2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_confirmarPopupPopupConfir2"), anchor, flags);
	}
	
	/**
	 * DhtmlZOrderManagerLayerContainer: with default state.
	 *		.id : DhtmlZOrderManagerLayerContainer
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_dhtmlZOrderManagerLayerCo() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_dhtmlZOrderManagerLayerCo"));
	}
	/**
	 * DhtmlZOrderManagerLayerContainer: with specific test context and state.
	 *		.id : DhtmlZOrderManagerLayerContainer
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_dhtmlZOrderManagerLayerCo(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_dhtmlZOrderManagerLayerCo"), anchor, flags);
	}
	
	/**
	 * idDocPrincipal: with default state.
	 *		.id : idDocPrincipal
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idDocPrincipal() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipal"));
	}
	/**
	 * idDocPrincipal: with specific test context and state.
	 *		.id : idDocPrincipal
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idDocPrincipal(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipal"), anchor, flags);
	}
	
	/**
	 * idDocPrincipalMsgDlg: with default state.
	 *		.id : idDocPrincipal::msgDlg
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idDocPrincipalMsgDlg() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipalMsgDlg"));
	}
	/**
	 * idDocPrincipalMsgDlg: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idDocPrincipalMsgDlg(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipalMsgDlg"), anchor, flags);
	}
	
	/**
	 * idDocPrincipalMsgDlg_cnt: with default state.
	 *		.id : idDocPrincipal::msgDlg::_cnt
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idDocPrincipalMsgDlg_cnt() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipalMsgDlg_cnt"));
	}
	/**
	 * idDocPrincipalMsgDlg_cnt: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::_cnt
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idDocPrincipalMsgDlg_cnt(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipalMsgDlg_cnt"), anchor, flags);
	}
	
	/**
	 * idDocPrincipalMsgDlg_ticn: with default state.
	 *		.id : idDocPrincipal::msgDlg::_ticn
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idDocPrincipalMsgDlg_ticn() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipalMsgDlg_ticn"));
	}
	/**
	 * idDocPrincipalMsgDlg_ticn: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::_ticn
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idDocPrincipalMsgDlg_ticn(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipalMsgDlg_ticn"), anchor, flags);
	}
	
	/**
	 * idDocPrincipalMsgDlg_ttxt: with default state.
	 *		.id : idDocPrincipal::msgDlg::_ttxt
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_idDocPrincipalMsgDlg_ttxt() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipalMsgDlg_ttxt"));
	}
	/**
	 * idDocPrincipalMsgDlg_ttxt: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::_ttxt
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_idDocPrincipalMsgDlg_ttxt(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idDocPrincipalMsgDlg_ttxt"), anchor, flags);
	}
	
	/**
	 * idPgTplGroupLayoutMenu: with default state.
	 *		.id : idPgTpl:groupLayoutMenu
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplGroupLayoutMenu() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplGroupLayoutMenu"));
	}
	/**
	 * idPgTplGroupLayoutMenu: with specific test context and state.
	 *		.id : idPgTpl:groupLayoutMenu
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplGroupLayoutMenu(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplGroupLayoutMenu"), anchor, flags);
	}
	
	/**
	 * idPgTplIdPBLHeader: with default state.
	 *		.id : idPgTpl:idPBLHeader
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplIdPBLHeader() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplIdPBLHeader"));
	}
	/**
	 * idPgTplIdPBLHeader: with specific test context and state.
	 *		.id : idPgTpl:idPBLHeader
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplIdPBLHeader(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplIdPBLHeader"), anchor, flags);
	}
	
	/**
	 * idPgTplIdPaBoLyUsuario: with default state.
	 *		.id : idPgTpl:idPaBoLyUsuario
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_idPgTplIdPaBoLyUsuario() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplIdPaBoLyUsuario"));
	}
	/**
	 * idPgTplIdPaBoLyUsuario: with specific test context and state.
	 *		.id : idPgTpl:idPaBoLyUsuario
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 1
	 */
	protected GuiTestObject html_idPgTplIdPaBoLyUsuario(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplIdPaBoLyUsuario"), anchor, flags);
	}
	
	/**
	 * idPgTplPglRequerimientos: with default state.
	 *		.id : idPgTpl:pglRequerimientos
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplPglRequerimientos() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplPglRequerimientos"));
	}
	/**
	 * idPgTplPglRequerimientos: with specific test context and state.
	 *		.id : idPgTpl:pglRequerimientos
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_idPgTplPglRequerimientos(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_idPgTplPglRequerimientos"), anchor, flags);
	}
	
	/**
	 * info: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://192.168.203.10/sigfe/afr/info.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_info() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_info"));
	}
	/**
	 * info: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://192.168.203.10/sigfe/afr/info.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_info(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_info"), anchor, flags);
	}
	
	/**
	 * RemodelaciónDeOficinasDeLaFiscalíaYTribunalDeCuentas: with default state.
	 *		.id : 
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_remodelaciónDeOficinasDe() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_remodelaciónDeOficinasDe"));
	}
	/**
	 * RemodelaciónDeOficinasDeLaFiscalíaYTribunalDeCuentas: with specific test context and state.
	 *		.id : 
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_remodelaciónDeOficinasDe(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_remodelaciónDeOficinasDe"), anchor, flags);
	}
	
	/**
	 * CambiarTamaño: with default state.
	 *		.text : 
	 * 		.href : 
	 * 		.id : idDocPrincipal::msgDlg::_ree
	 * 		.title : Cambiar Tamaño
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_cambiarTamaño() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_cambiarTamaño"));
	}
	/**
	 * CambiarTamaño: with specific test context and state.
	 *		.text : 
	 * 		.href : 
	 * 		.id : idDocPrincipal::msgDlg::_ree
	 * 		.title : Cambiar Tamaño
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_cambiarTamaño(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_cambiarTamaño"), anchor, flags);
	}
	
	/**
	 * Cerrar: with default state.
	 *		.text : 
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idDocPrincipal::msgDlg::close
	 * 		.title : Cerrar
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_cerrar() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_cerrar"));
	}
	/**
	 * Cerrar: with specific test context and state.
	 *		.text : 
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idDocPrincipal::msgDlg::close
	 * 		.title : Cerrar
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_cerrar(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_cerrar"), anchor, flags);
	}
	
	/**
	 * idPgTplCmdLnkGuardarBorradorInferior: with default state.
	 *		.text : Guardar Digitado
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:cmdLnkGuardarBorradorInferior
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_idPgTplCmdLnkGuardarBorra() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplCmdLnkGuardarBorra"));
	}
	/**
	 * idPgTplCmdLnkGuardarBorradorInferior: with specific test context and state.
	 *		.text : Guardar Digitado
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:cmdLnkGuardarBorradorInferior
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_idPgTplCmdLnkGuardarBorra(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplCmdLnkGuardarBorra"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrps0Cci1ClkAddConc: with default state.
	 *		.text : Agregar Concepto Presupuestario
	 * 		.id : idPgTpl:itAgrps:0:cci1:clkAddConc
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps0Cci1ClkAdd() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps0Cci1ClkAdd"));
	}
	/**
	 * idPgTplItAgrps0Cci1ClkAddConc: with specific test context and state.
	 *		.text : Agregar Concepto Presupuestario
	 * 		.id : idPgTpl:itAgrps:0:cci1:clkAddConc
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps0Cci1ClkAdd(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps0Cci1ClkAdd"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrps1Cci1ClkAddConc: with default state.
	 *		.text : Agregar Concepto Presupuestario
	 * 		.id : idPgTpl:itAgrps:1:cci1:clkAddConc
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps1Cci1ClkAdd() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps1Cci1ClkAdd"));
	}
	/**
	 * idPgTplItAgrps1Cci1ClkAddConc: with specific test context and state.
	 *		.text : Agregar Concepto Presupuestario
	 * 		.id : idPgTpl:itAgrps:1:cci1:clkAddConc
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps1Cci1ClkAdd(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps1Cci1ClkAdd"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrps2Cci1ClkAddConc: with default state.
	 *		.text : Agregar Concepto Presupuestario
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:itAgrps:2:cci1:clkAddConc
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps2Cci1ClkAdd() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps2Cci1ClkAdd"));
	}
	/**
	 * idPgTplItAgrps2Cci1ClkAddConc: with specific test context and state.
	 *		.text : Agregar Concepto Presupuestario
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-multiprograma-registro ...
	 * 		.id : idPgTpl:itAgrps:2:cci1:clkAddConc
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplItAgrps2Cci1ClkAdd(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplItAgrps2Cci1ClkAdd"), anchor, flags);
	}
	
	/**
	 * Requerimiento: with default state.
	 *		.text : Requerimiento
	 * 		.id : 
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenidaInicio?_adf.no-new-window-redirect=t ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_requerimiento() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_requerimiento"));
	}
	/**
	 * Requerimiento: with specific test context and state.
	 *		.text : Requerimiento
	 * 		.id : 
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenidaInicio?_adf.no-new-window-redirect=t ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_requerimiento(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_requerimiento"), anchor, flags);
	}
	
	/**
	 * Seleccione: with default state.
	 *		.text : Seleccione... Ley de Presupuestos Fondos no afectos a Ley
	 * 		.id : idPgTpl:idSeOnChTipoDemanda::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeOnChTipoDemanda
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione"));
	}
	/**
	 * Seleccione: with specific test context and state.
	 *		.text : Seleccione... Ley de Presupuestos Fondos no afectos a Ley
	 * 		.id : idPgTpl:idSeOnChTipoDemanda::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeOnChTipoDemanda
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione"), anchor, flags);
	}
	
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC10SbrACCCat1: with default state.
	 *		.id : svwCombinacCatalogos:trACC1:0:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:0:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb"));
	}
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC10SbrACCCat1: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC1:0:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:0:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb"), anchor, flags);
	}
	
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC17SbrACCCat1: with default state.
	 *		.id : svwCombinacCatalogos:trACC1:7:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:7:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb2() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb2"));
	}
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC17SbrACCCat1: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC1:7:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:7:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb2(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb2"), anchor, flags);
	}
	
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC120SbrACCCat1: with default state.
	 *		.id : svwCombinacCatalogos:trACC1:20:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:20:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb3() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb3"));
	}
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC120SbrACCCat1: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC1:20:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:20:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb3(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb3"), anchor, flags);
	}
	
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC10SbrACCCat1: with default state.
	 *		.id : svwCombinacCatalogos:trACC1:0:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:0:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb4() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb4"));
	}
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC10SbrACCCat1: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC1:0:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:0:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb4(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb4"), anchor, flags);
	}
	
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC11SbrACCCat1: with default state.
	 *		.id : svwCombinacCatalogos:trACC1:1:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:1:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb5() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb5"));
	}
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC11SbrACCCat1: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC1:1:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:1:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb5(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb5"), anchor, flags);
	}
	
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC12SbrACCCat1: with default state.
	 *		.id : svwCombinacCatalogos:trACC1:2:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:2:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb6() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb6"));
	}
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC12SbrACCCat1: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC1:2:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:2:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb6(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb6"), anchor, flags);
	}
	
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC13SbrACCCat1: with default state.
	 *		.id : svwCombinacCatalogos:trACC1:3:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:3:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb7() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb7"));
	}
	/**
	 * rbCatalogo1svwCombinacCatalogosTrACC13SbrACCCat1: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC1:3:sbrACCCat1::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC1:3:sbrACCCat1
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo1
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo1svwComb7(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo1svwComb7"), anchor, flags);
	}
	
	/**
	 * rbCatalogo2svwCombinacCatalogosTrACC21SbrACCCat2: with default state.
	 *		.id : svwCombinacCatalogos:trACC2:1:sbrACCCat2::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC2:1:sbrACCCat2
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo2
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo2svwComb() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo2svwComb"));
	}
	/**
	 * rbCatalogo2svwCombinacCatalogosTrACC21SbrACCCat2: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC2:1:sbrACCCat2::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC2:1:sbrACCCat2
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo2
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo2svwComb(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo2svwComb"), anchor, flags);
	}
	
	/**
	 * rbCatalogo2svwCombinacCatalogosTrACC27SbrACCCat2: with default state.
	 *		.id : svwCombinacCatalogos:trACC2:7:sbrACCCat2::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC2:7:sbrACCCat2
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo2
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo2svwComb2() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo2svwComb2"));
	}
	/**
	 * rbCatalogo2svwCombinacCatalogosTrACC27SbrACCCat2: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC2:7:sbrACCCat2::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC2:7:sbrACCCat2
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo2
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo2svwComb2(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo2svwComb2"), anchor, flags);
	}
	
	/**
	 * rbCatalogo2svwCombinacCatalogosTrACC212SbrACCCat2: with default state.
	 *		.id : svwCombinacCatalogos:trACC2:12:sbrACCCat2::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC2:12:sbrACCCat2
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo2
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo2svwComb3() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo2svwComb3"));
	}
	/**
	 * rbCatalogo2svwCombinacCatalogosTrACC212SbrACCCat2: with specific test context and state.
	 *		.id : svwCombinacCatalogos:trACC2:12:sbrACCCat2::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:trACC2:12:sbrACCCat2
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo2
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo2svwComb3(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo2svwComb3"), anchor, flags);
	}
	
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre0SbrACCCat3: with default state.
	 *		.id : svwCombinacCatalogos:treeTre:0:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:0:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb"));
	}
	/**
	 * rbCatalogo3svwCombinacCatalogosTreeTre0SbrACCCat3: with specific test context and state.
	 *		.id : svwCombinacCatalogos:treeTre:0:sbrACCCat3::content
	 * 		.type : radio
	 * 		.value : svwCombinacCatalogos:treeTre:0:sbrACCCat3
	 * 		.title : 
	 * 		.class : Html.INPUT.radio
	 * 		.name : rbCatalogo3
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject radioButton_rbCatalogo3svwComb(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("radioButton_rbCatalogo3svwComb"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_2"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_2"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_3() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_3"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_3(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_3"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_4() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_4"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_4(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_4"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_5() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_5"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_5(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_5"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_6() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_6"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_6(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_6"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_7() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_7"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_7(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_7"), anchor, flags);
	}
	
	/**
	 * HtmlTable_1: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_1() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_1"));
	}
	/**
	 * HtmlTable_1: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 1
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_1(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_1"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id11Menu: with default state.
	 *		.id : idPgTpl:j_id11::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id11Menu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id11Menu"));
	}
	/**
	 * idPgTplJ_id11Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id11::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id11Menu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id11Menu"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id22Menu: with default state.
	 *		.id : idPgTpl:j_id22::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id22Menu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id22Menu"));
	}
	/**
	 * idPgTplJ_id22Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id22::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id22Menu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id22Menu"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id23Menu: with default state.
	 *		.id : idPgTpl:j_id23::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id23Menu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id23Menu"));
	}
	/**
	 * idPgTplJ_id23Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id23::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id23Menu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id23Menu"), anchor, flags);
	}
	
	/**
	 * pt2ContenedorMsj: with default state.
	 *		.id : pt2:contenedorMsj
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_pt2ContenedorMsj() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_pt2ContenedorMsj"));
	}
	/**
	 * pt2ContenedorMsj: with specific test context and state.
	 *		.id : pt2:contenedorMsj
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_pt2ContenedorMsj(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_pt2ContenedorMsj"), anchor, flags);
	}
	
	/**
	 * _2101001003: with default state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 2101001003
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_CodigoConcepto() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_CodigoConcepto"));
	}
	/**
	 * _2101001003: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 2101001003
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_CodigoConcepto(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_CodigoConcepto"), anchor, flags);
	}
	
	/**
	 * _210100103: with default state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 210100103
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__210100103() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__210100103"));
	}
	/**
	 * _210100103: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 210100103
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__210100103(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__210100103"), anchor, flags);
	}
	
	/**
	 * _2204001: with default state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 2204001
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__2204001() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__2204001"));
	}
	/**
	 * _2204001: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 2204001
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__2204001(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__2204001"), anchor, flags);
	}
	
	/**
	 * _2205001: with default state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 2205001
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__2205001() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__2205001"));
	}
	/**
	 * _2205001: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 2205001
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__2205001(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__2205001"), anchor, flags);
	}
	
	/**
	 * _2205002: with default state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 2205002
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__2205002() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__2205002"));
	}
	/**
	 * _2205002: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 2205002
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__2205002(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__2205002"), anchor, flags);
	}
	
	/**
	 * _2205005: with default state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 2205005
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__2205005() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__2205005"));
	}
	/**
	 * _2205005: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 2205005
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__2205005(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__2205005"), anchor, flags);
	}
	
	/**
	 * _2907001: with default state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 2907001
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__2907001() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__2907001"));
	}
	/**
	 * _2907001: with specific test context and state.
	 *		.id : svwBuscarConceptoSM:intxCodigoCpt::content
	 * 		.type : text
	 * 		.title : 2907001
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarConceptoSM:intxCodigoCpt
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__2907001(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__2907001"), anchor, flags);
	}
	
	/**
	 * idPgTplDescripcion: with default state.
	 *		.id : idPgTpl:descripcion::content
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : idPgTpl:descripcion
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplDescripcion() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplDescripcion"));
	}
	/**
	 * idPgTplDescripcion: with specific test context and state.
	 *		.id : idPgTpl:descripcion::content
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : idPgTpl:descripcion
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplDescripcion(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplDescripcion"), anchor, flags);
	}
	
	/**
	 * idPgTplTitulo: with default state.
	 *		.id : idPgTpl:titulo::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:titulo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplTitulo() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplTitulo"));
	}
	/**
	 * idPgTplTitulo: with specific test context and state.
	 *		.id : idPgTpl:titulo::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:titulo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplTitulo(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplTitulo"), anchor, flags);
	}
	
	/**
	 * j_password: with default state.
	 *		.id : 
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : j_password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_password() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_password"));
	}
	/**
	 * j_password: with specific test context and state.
	 *		.id : 
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : j_password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_password(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_password"), anchor, flags);
	}
	
	/**
	 * j_username: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : j_username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_username() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_username"));
	}
	/**
	 * j_username: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : j_username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_username(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_username"), anchor, flags);
	}
	
	/**
	 * svwAgregarConceptoPresPopUpTAddCP0Valor: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:0:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:0:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop"));
	}
	/**
	 * svwAgregarConceptoPresPopUpTAddCP0Valor: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:0:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:0:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop"), anchor, flags);
	}
	
	/**
	 * svwAgregarConceptoPresPopUpTAddCP2Valor: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:2:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:2:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop10() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop10"));
	}
	/**
	 * svwAgregarConceptoPresPopUpTAddCP2Valor: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:2:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:2:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop10(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop10"), anchor, flags);
	}
	
	/**
	 * svwAgregarConceptoPresPopUpTAddCP0Valor: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:0:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:0:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop11() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop11"));
	}
	/**
	 * svwAgregarConceptoPresPopUpTAddCP0Valor: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:0:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:0:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop11(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop11"), anchor, flags);
	}
	
	/**
	 * svwAgregarConceptoPresPopUpTAddCP1Valor: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:1:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:1:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop2"));
	}
	/**
	 * svwAgregarConceptoPresPopUpTAddCP1Valor: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:1:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:1:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop2"), anchor, flags);
	}
	
	/**
	 * svwAgregarConceptoPresPopUpTAddCP2Valor: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:2:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:2:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop3() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop3"));
	}
	/**
	 * svwAgregarConceptoPresPopUpTAddCP2Valor: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:2:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:2:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop3(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop3"), anchor, flags);
	}
	
	/**
	 * svwAgregarConceptoPresPopUpTAddCP3Valor: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:3:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:3:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop4() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop4"));
	}
	/**
	 * svwAgregarConceptoPresPopUpTAddCP3Valor: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:3:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:3:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop4(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop4"), anchor, flags);
	}
	
	/**
	 * svwAgregarConceptoPresPopUpTAddCP0Valor: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:0:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:0:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop5() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop5"));
	}
	/**
	 * svwAgregarConceptoPresPopUpTAddCP0Valor: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:0:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:0:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop5(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop5"), anchor, flags);
	}
	
	/**
	 * svwAgregarConceptoPresPopUpTAddCP1Valor: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:1:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:1:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop6() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop6"));
	}
	/**
	 * svwAgregarConceptoPresPopUpTAddCP1Valor: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:1:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:1:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop6(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop6"), anchor, flags);
	}
	
	/**
	 * svwAgregarConceptoPresPopUpTAddCP2Valor: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:2:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:2:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop7() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop7"));
	}
	/**
	 * svwAgregarConceptoPresPopUpTAddCP2Valor: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:2:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:2:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop7(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop7"), anchor, flags);
	}
	
	/**
	 * svwAgregarConceptoPresPopUpTAddCP0Valor: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:0:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:0:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop8() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop8"));
	}
	/**
	 * svwAgregarConceptoPresPopUpTAddCP0Valor: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:0:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:0:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop8(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop8"), anchor, flags);
	}
	
	/**
	 * svwAgregarConceptoPresPopUpTAddCP1Valor: with default state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:1:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:1:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop9() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop9"));
	}
	/**
	 * svwAgregarConceptoPresPopUpTAddCP1Valor: with specific test context and state.
	 *		.id : svwAgregarConceptoPresPopUp:tAddCP:1:valor::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : svwAgregarConceptoPresPopUp:tAddCP:1:valor
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_svwAgregarConceptoPresPop9(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_svwAgregarConceptoPresPop9"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point PV_Confirma_Generar object in the SUT.
	 */
	protected IFtVerificationPoint PV_Confirma_GenerarVP() 
	{
		return vp("PV_Confirma_Generar");
	}
	protected IFtVerificationPoint PV_Confirma_GenerarVP(TestObject anchor)
	{
		return vp("PV_Confirma_Generar", anchor);
	}
	
	/**
	 * Locate and return the verification point PV_Generacion_RP object in the SUT.
	 */
	protected IFtVerificationPoint PV_Generacion_RPVP() 
	{
		return vp("PV_Generacion_RP");
	}
	protected IFtVerificationPoint PV_Generacion_RPVP(TestObject anchor)
	{
		return vp("PV_Generacion_RP", anchor);
	}
	
	/**
	 * Locate and return the verification point PV_Guardar_Digitado object in the SUT.
	 */
	protected IFtVerificationPoint PV_Guardar_DigitadoVP() 
	{
		return vp("PV_Guardar_Digitado");
	}
	protected IFtVerificationPoint PV_Guardar_DigitadoVP(TestObject anchor)
	{
		return vp("PV_Guardar_Digitado", anchor);
	}
	
	

	protected RP_Multiple_Gastos_Moneda_Nacional_GenerarHelper()
	{
		setScriptName("Modulos.Requerimiento.RP_Multiple_Gastos_Moneda_Nacional_Generar");
	}
	
}

