// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Modulos.Requerimiento;
import Librerias.Funciones_Globales;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>RP_Multiple_Gastos_Moneda_Nacional_Aprobar</b><br>
 * Generated     : <b>2014/08/27 17:37:56</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 <br>
 * 
 * @since  agosto 27, 2014
 * @author cpena
 */
public abstract class RP_Multiple_Gastos_Moneda_Nacional_AprobarHelper extends Librerias.Funciones_Globales
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox 17.0
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox 17.0
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit2"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit2"), anchor, flags);
	}
	
	/**
	 * Aprobarsubmit: with default state.
	 *		.id : idVerReqAprobacion:comp_BotonConfSeleccion_1:botonConfSelec_1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aprobarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aprobarsubmit"));
	}
	/**
	 * Aprobarsubmit: with specific test context and state.
	 *		.id : idVerReqAprobacion:comp_BotonConfSeleccion_1:botonConfSelec_1
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aprobarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aprobarsubmit"), anchor, flags);
	}
	
	/**
	 * Back: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Back
	 */
	protected GuiTestObject button_back() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_back"));
	}
	/**
	 * Back: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Back
	 */
	protected GuiTestObject button_back(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_back"), anchor, flags);
	}
	
	/**
	 * bookmarksMenuButtonContainer: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : bookmarks-menu-button-container
	 */
	protected GuiTestObject button_bookmarksMenuButtonCont() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_bookmarksMenuButtonCont"));
	}
	/**
	 * bookmarksMenuButtonContainer: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : bookmarks-menu-button-container
	 */
	protected GuiTestObject button_bookmarksMenuButtonCont(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_bookmarksMenuButtonCont"), anchor, flags);
	}
	
	/**
	 * Buscarsubmit: with default state.
	 *		.id : idTmpB:componenteBotonBuscar:boton_buscar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit"));
	}
	/**
	 * Buscarsubmit: with specific test context and state.
	 *		.id : idTmpB:componenteBotonBuscar:boton_buscar
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit"), anchor, flags);
	}
	
	/**
	 * Forward: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Forward
	 */
	protected GuiTestObject button_forward() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_forward"));
	}
	/**
	 * Forward: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Forward
	 */
	protected GuiTestObject button_forward(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_forward"), anchor, flags);
	}
	
	/**
	 * Home: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Home
	 */
	protected GuiTestObject button_home() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_home"));
	}
	/**
	 * Home: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Home
	 */
	protected GuiTestObject button_home(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_home"), anchor, flags);
	}
	
	/**
	 * Reload: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Reload
	 */
	protected GuiTestObject button_reload() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_reload"));
	}
	/**
	 * Reload: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Reload
	 */
	protected GuiTestObject button_reload(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_reload"), anchor, flags);
	}
	
	/**
	 * searchContainer: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : search-container
	 */
	protected GuiTestObject button_searchContainer() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_searchContainer"));
	}
	/**
	 * searchContainer: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : search-container
	 */
	protected GuiTestObject button_searchContainer(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_searchContainer"), anchor, flags);
	}
	
	/**
	 * socialToolbarItem: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : social-toolbar-item
	 */
	protected GuiTestObject button_socialToolbarItem() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_socialToolbarItem"));
	}
	/**
	 * socialToolbarItem: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : social-toolbar-item
	 */
	protected GuiTestObject button_socialToolbarItem(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_socialToolbarItem"), anchor, flags);
	}
	
	/**
	 * Stop: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Stop
	 */
	protected GuiTestObject button_stop() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_stop"));
	}
	/**
	 * Stop: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : Stop
	 */
	protected GuiTestObject button_stop(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_stop"), anchor, flags);
	}
	
	/**
	 * ToolbarButton: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : 
	 */
	protected GuiTestObject button_toolbarButton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_toolbarButton"));
	}
	/**
	 * ToolbarButton: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : 
	 */
	protected GuiTestObject button_toolbarButton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_toolbarButton"), anchor, flags);
	}
	
	/**
	 * urlbarContainer: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : urlbar-container
	 */
	protected GuiTestObject button_urlbarContainer() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_urlbarContainer"));
	}
	/**
	 * urlbarContainer: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : urlbar-container
	 */
	protected GuiTestObject button_urlbarContainer(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_urlbarContainer"), anchor, flags);
	}
	
	/**
	 * urlbarSearchSplitter: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : urlbar-search-splitter
	 */
	protected GuiTestObject button_urlbarSearchSplitter() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_urlbarSearchSplitter"));
	}
	/**
	 * urlbarSearchSplitter: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : urlbar-search-splitter
	 */
	protected GuiTestObject button_urlbarSearchSplitter(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_urlbarSearchSplitter"), anchor, flags);
	}
	
	/**
	 * windowControls: with default state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : window-controls
	 */
	protected GuiTestObject button_windowControls() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_windowControls"));
	}
	/**
	 * windowControls: with specific test context and state.
	 *		.class : Html.HtmlBrowser.ToolbarButton
	 * 		.name : window-controls
	 */
	protected GuiTestObject button_windowControls(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_windowControls"), anchor, flags);
	}
	
	/**
	 * aboutBlank: with default state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : about:blank
	 */
	protected DocumentTestObject document_aboutBlank() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_aboutBlank"));
	}
	/**
	 * aboutBlank: with specific test context and state.
	 *		.title : 
	 * 		.class : Html.HtmlDocument
	 * 		.url : about:blank
	 */
	protected DocumentTestObject document_aboutBlank(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_aboutBlank"), anchor, flags);
	}
	
	/**
	 * confirmarPopupPanelMensajeConfirmacion: with default state.
	 *		.id : confirmarPopup:panelMensajeConfirmacion
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 2
	 */
	protected GuiTestObject html_confirmarPopupPanelMensaj() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_confirmarPopupPanelMensaj"));
	}
	/**
	 * confirmarPopupPanelMensajeConfirmacion: with specific test context and state.
	 *		.id : confirmarPopup:panelMensajeConfirmacion
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 2
	 */
	protected GuiTestObject html_confirmarPopupPanelMensaj(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_confirmarPopupPanelMensaj"), anchor, flags);
	}
	
	/**
	 * BúsquedaDeRequerimientosPresupuestarios: with default state.
	 *		.id : 
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_búsquedaDeRequerimientos() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_búsquedaDeRequerimientos"));
	}
	/**
	 * BúsquedaDeRequerimientosPresupuestarios: with specific test context and state.
	 *		.id : 
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_búsquedaDeRequerimientos(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_búsquedaDeRequerimientos"), anchor, flags);
	}
	
	/**
	 * VisualizarRequerimientoPresupuestario: with default state.
	 *		.id : 
	 * 		.value : 
	 * 		.class : Html.LABEL
	 * 		.title : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_visualizarRequerimientoP() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_visualizarRequerimientoP"));
	}
	/**
	 * VisualizarRequerimientoPresupuestario: with specific test context and state.
	 *		.id : 
	 * 		.value : 
	 * 		.class : Html.LABEL
	 * 		.title : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_visualizarRequerimientoP(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_visualizarRequerimientoP"), anchor, flags);
	}
	
	/**
	 * idTmpBIdTbRqB0LinkVisualizar: with default state.
	 *		.text : Visualizar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-buscar/busquedaRequeri ...
	 * 		.id : idTmpB:idTbRqB:0:linkVisualizar
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_idTmpBIdTbRqB0LinkVisuali() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idTmpBIdTbRqB0LinkVisuali"));
	}
	/**
	 * idTmpBIdTbRqB0LinkVisualizar: with specific test context and state.
	 *		.text : Visualizar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-buscar/busquedaRequeri ...
	 * 		.id : idTmpB:idTbRqB:0:linkVisualizar
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_idTmpBIdTbRqB0LinkVisuali(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idTmpBIdTbRqB0LinkVisuali"), anchor, flags);
	}
	
	/**
	 * IrABienvenida: with default state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-buscar/busquedaRequeri ...
	 * 		.id : idTmpB:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida"));
	}
	/**
	 * IrABienvenida: with specific test context and state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-buscar/busquedaRequeri ...
	 * 		.id : idTmpB:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida"), anchor, flags);
	}
	
	/**
	 * IrABienvenida: with default state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=10ay1znz2_14&_afrLo ...
	 * 		.id : idPgTpl:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida2"));
	}
	/**
	 * IrABienvenida: with specific test context and state.
	 *		.text : noMostrar
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=10ay1znz2_14&_afrLo ...
	 * 		.id : idPgTpl:goBienvenida
	 * 		.title : Ir a Bienvenida!
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida2"), anchor, flags);
	}
	
	/**
	 * Requerimiento: with default state.
	 *		.text : Requerimiento
	 * 		.id : 
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=10ay1znz2_14&_afrLo ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_requerimiento() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_requerimiento"));
	}
	/**
	 * Requerimiento: with specific test context and state.
	 *		.text : Requerimiento
	 * 		.id : 
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=10ay1znz2_14&_afrLo ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_requerimiento(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_requerimiento"), anchor, flags);
	}
	
	/**
	 * BúsquedaDeRequerimientosPresupuestarios: with default state.
	 *		.class : Html.HtmlBrowser.Tab
	 * 		.name : Búsqueda de Requerimientos Presupuestarios
	 */
	protected BrowserTabTestObject pageTab_búsquedaDeRequerimient() 
	{
		return new BrowserTabTestObject(
                        getMappedTestObject("pageTab_búsquedaDeRequerimient"));
	}
	/**
	 * BúsquedaDeRequerimientosPresupuestarios: with specific test context and state.
	 *		.class : Html.HtmlBrowser.Tab
	 * 		.name : Búsqueda de Requerimientos Presupuestarios
	 */
	protected BrowserTabTestObject pageTab_búsquedaDeRequerimient(TestObject anchor, long flags) 
	{
		return new BrowserTabTestObject(
                        getMappedTestObject("pageTab_búsquedaDeRequerimient"), anchor, flags);
	}
	
	/**
	 * OpenANewTab: with default state.
	 *		.class : Html.HtmlBrowser.Tab
	 * 		.name : Open a new tab
	 */
	protected BrowserTabTestObject pageTab_openANewTab() 
	{
		return new BrowserTabTestObject(
                        getMappedTestObject("pageTab_openANewTab"));
	}
	/**
	 * OpenANewTab: with specific test context and state.
	 *		.class : Html.HtmlBrowser.Tab
	 * 		.name : Open a new tab
	 */
	protected BrowserTabTestObject pageTab_openANewTab(TestObject anchor, long flags) 
	{
		return new BrowserTabTestObject(
                        getMappedTestObject("pageTab_openANewTab"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_2"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_2"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_3() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_3"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_3(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_3"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id11Menu: with default state.
	 *		.id : idPgTpl:j_id11::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id11Menu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id11Menu"));
	}
	/**
	 * idPgTplJ_id11Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id11::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id11Menu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id11Menu"), anchor, flags);
	}
	
	/**
	 * _1164425: with default state.
	 *		.id : idTmpB:idTransaccional::content
	 * 		.type : text
	 * 		.title : 1.164.425
	 * 		.class : Html.INPUT.text
	 * 		.name : idTmpB:idTransaccional
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__1164425() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__1164425"));
	}
	/**
	 * _1164425: with specific test context and state.
	 *		.id : idTmpB:idTransaccional::content
	 * 		.type : text
	 * 		.title : 1.164.425
	 * 		.class : Html.INPUT.text
	 * 		.name : idTmpB:idTransaccional
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__1164425(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__1164425"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point PV_BusquedaRP object in the SUT.
	 */
	protected IFtVerificationPoint PV_BusquedaRPVP() 
	{
		return vp("PV_BusquedaRP");
	}
	protected IFtVerificationPoint PV_BusquedaRPVP(TestObject anchor)
	{
		return vp("PV_BusquedaRP", anchor);
	}
	
	/**
	 * Locate and return the verification point PV_ConfirmaAprobacion object in the SUT.
	 */
	protected IFtVerificationPoint PV_ConfirmaAprobacionVP() 
	{
		return vp("PV_ConfirmaAprobacion");
	}
	protected IFtVerificationPoint PV_ConfirmaAprobacionVP(TestObject anchor)
	{
		return vp("PV_ConfirmaAprobacion", anchor);
	}
	
	/**
	 * Locate and return the verification point PV_RPAprobado object in the SUT.
	 */
	protected IFtVerificationPoint PV_RPAprobadoVP() 
	{
		return vp("PV_RPAprobado");
	}
	protected IFtVerificationPoint PV_RPAprobadoVP(TestObject anchor)
	{
		return vp("PV_RPAprobado", anchor);
	}
	
	/**
	 * Locate and return the verification point PV_RPGenerado_Encontrado object in the SUT.
	 */
	protected IFtVerificationPoint PV_RPGenerado_EncontradoVP() 
	{
		return vp("PV_RPGenerado_Encontrado");
	}
	protected IFtVerificationPoint PV_RPGenerado_EncontradoVP(TestObject anchor)
	{
		return vp("PV_RPGenerado_Encontrado", anchor);
	}
	
	

	protected RP_Multiple_Gastos_Moneda_Nacional_AprobarHelper()
	{
		setScriptName("Modulos.Requerimiento.RP_Multiple_Gastos_Moneda_Nacional_Aprobar");
	}
	
}

