// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Modulos.Requerimiento;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>RP_Multiple_Gastos_Moneda_Nacional_Aprobar</b><br>
 * Generated     : <b>2014/08/26 10:17:40</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 <br>
 * 
 * @since  agosto 26, 2014
 * @author cpena
 */
public abstract class RP_Multiple_Gastos_Moneda_Nacional_AprobarHelper extends RationalTestScript
{
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit2"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit2"), anchor, flags);
	}
	
	/**
	 * Aprobarsubmit: with default state.
	 *		.id : idVerReqAprobacion:comp_BotonConfSeleccion_1:botonConfSelec_1
	 * 		.type : submit
	 * 		.value : 
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aprobarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aprobarsubmit"));
	}
	/**
	 * Aprobarsubmit: with specific test context and state.
	 *		.id : idVerReqAprobacion:comp_BotonConfSeleccion_1:botonConfSelec_1
	 * 		.type : submit
	 * 		.value : 
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aprobarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aprobarsubmit"), anchor, flags);
	}
	
	/**
	 * Buscarsubmit: with default state.
	 *		.id : idTmpB:componenteBotonBuscar:boton_buscar
	 * 		.type : submit
	 * 		.value : 
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit"));
	}
	/**
	 * Buscarsubmit: with specific test context and state.
	 *		.id : idTmpB:componenteBotonBuscar:boton_buscar
	 * 		.type : submit
	 * 		.value : 
	 * 		.class : Html.BUTTON
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit"), anchor, flags);
	}
	
	/**
	 * idTmpBIdTbRqB0LinkVisualizar: with default state.
	 *		.text : Visualizar
	 * 		.id : idTmpB:idTbRqB:0:linkVisualizar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-buscar/busquedaRequeri ...
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_idTmpBIdTbRqB0LinkVisuali() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idTmpBIdTbRqB0LinkVisuali"));
	}
	/**
	 * idTmpBIdTbRqB0LinkVisualizar: with specific test context and state.
	 *		.text : Visualizar
	 * 		.id : idTmpB:idTbRqB:0:linkVisualizar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-buscar/busquedaRequeri ...
	 * 		.class : Html.A
	 * 		.title : 
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_idTmpBIdTbRqB0LinkVisuali(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idTmpBIdTbRqB0LinkVisuali"), anchor, flags);
	}
	
	/**
	 * IrABienvenida: with default state.
	 *		.text : noMostrar
	 * 		.id : idTmpB:goBienvenida
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-buscar/busquedaRequeri ...
	 * 		.class : Html.A
	 * 		.title : Ir a Bienvenida!
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida"));
	}
	/**
	 * IrABienvenida: with specific test context and state.
	 *		.text : noMostrar
	 * 		.id : idTmpB:goBienvenida
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-requerimiento-buscar/busquedaRequeri ...
	 * 		.class : Html.A
	 * 		.title : Ir a Bienvenida!
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida"), anchor, flags);
	}
	
	/**
	 * IrABienvenida: with default state.
	 *		.text : noMostrar
	 * 		.id : idPgTpl:goBienvenida
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=10ay1znz2_14&_afrLo ...
	 * 		.class : Html.A
	 * 		.title : Ir a Bienvenida!
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida2"));
	}
	/**
	 * IrABienvenida: with specific test context and state.
	 *		.text : noMostrar
	 * 		.id : idPgTpl:goBienvenida
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=10ay1znz2_14&_afrLo ...
	 * 		.class : Html.A
	 * 		.title : Ir a Bienvenida!
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_irABienvenida2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_irABienvenida2"), anchor, flags);
	}
	
	/**
	 * Requerimiento: with default state.
	 *		.text : Requerimiento
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=10ay1znz2_14&_afrLo ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_requerimiento() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_requerimiento"));
	}
	/**
	 * Requerimiento: with specific test context and state.
	 *		.text : Requerimiento
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenida?_adf.ctrl-state=10ay1znz2_14&_afrLo ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_requerimiento(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_requerimiento"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.class : Html.TABLE
	 * 		.title : 
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.class : Html.TABLE
	 * 		.title : 
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id11Menu: with default state.
	 *		.id : idPgTpl:j_id11::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id11Menu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id11Menu"));
	}
	/**
	 * idPgTplJ_id11Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id11::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id11Menu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id11Menu"), anchor, flags);
	}
	
	/**
	 * _1164425: with default state.
	 *		.id : idTmpB:idTransaccional::content
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 1.164.425
	 * 		.name : idTmpB:idTransaccional
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__1164425() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__1164425"));
	}
	/**
	 * _1164425: with specific test context and state.
	 *		.id : idTmpB:idTransaccional::content
	 * 		.type : text
	 * 		.class : Html.INPUT.text
	 * 		.title : 1.164.425
	 * 		.name : idTmpB:idTransaccional
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__1164425(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__1164425"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point HtmlTable_0_text object in the SUT.
	 */
	protected IFtVerificationPoint HtmlTable_0_textVP() 
	{
		return vp("HtmlTable_0_text");
	}
	protected IFtVerificationPoint HtmlTable_0_textVP(TestObject anchor)
	{
		return vp("HtmlTable_0_text", anchor);
	}
	
	

	protected RP_Multiple_Gastos_Moneda_Nacional_AprobarHelper()
	{
		setScriptName("Modulos.Requerimiento.RP_Multiple_Gastos_Moneda_Nacional_Aprobar");
	}
	
}

