// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Modulos.Compromiso;
import Librerias.Funciones_Globales;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>CP_Licitacion_Gastos_Moneda_Nacional_Generar</b><br>
 * Generated     : <b>2014/08/28 18:05:17</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 <br>
 * 
 * @since  agosto 28, 2014
 * @author cpena
 */
public abstract class CP_Licitacion_Gastos_Moneda_Nacional_GenerarHelper extends Librerias.Funciones_Globales
{
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : idDocPrincipal::msgDlg::cancel
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit"), anchor, flags);
	}
	
	/**
	 * Aceptarsubmit: with default state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit2"));
	}
	/**
	 * Aceptarsubmit: with specific test context and state.
	 *		.id : confirmarPopup:botonGrabarDistribucion
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_aceptarsubmit2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_aceptarsubmit2"), anchor, flags);
	}
	
	/**
	 * Agregarsubmit: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:comp_BotonAgregarDoc:botonAgregarDoc
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_agregarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_agregarsubmit"));
	}
	/**
	 * Agregarsubmit: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:comp_BotonAgregarDoc:botonAgregarDoc
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_agregarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_agregarsubmit"), anchor, flags);
	}
	
	/**
	 * Buscarsubmit: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:comp_BotonBuscarDoc:botonBuscarDocRef
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit"));
	}
	/**
	 * Buscarsubmit: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:comp_BotonBuscarDoc:botonBuscarDocRef
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_buscarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_buscarsubmit"), anchor, flags);
	}
	
	/**
	 * ConfirmarSelecciónsubmit: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:comp_BotonConfSeleccion:botonConfSelec
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi"));
	}
	/**
	 * ConfirmarSelecciónsubmit: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:comp_BotonConfSeleccion:botonConfSelec
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi"), anchor, flags);
	}
	
	/**
	 * ConfirmarSelecciónsubmit: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:componentepaso2de3:botonConfConce
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi2"));
	}
	/**
	 * ConfirmarSelecciónsubmit: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:componentepaso2de3:botonConfConce
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_confirmarSelecciónsubmi2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_confirmarSelecciónsubmi2"), anchor, flags);
	}
	
	/**
	 * Generarsubmit: with default state.
	 *		.id : idPgTpl:idCoboBotonGenerar:idCmbIrGenerarCompromiso
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_generarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_generarsubmit"));
	}
	/**
	 * Generarsubmit: with specific test context and state.
	 *		.id : idPgTpl:idCoboBotonGenerar:idCmbIrGenerarCompromiso
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_generarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_generarsubmit"), anchor, flags);
	}
	
	/**
	 * Ingresarsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Ingresar
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_ingresarsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_ingresarsubmit"));
	}
	/**
	 * Ingresarsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Ingresar
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_ingresarsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_ingresarsubmit"), anchor, flags);
	}
	
	/**
	 * paso1De1submit: with default state.
	 *		.id : buscarFechasCumplimientoPopup:cbp1:idCmbIrPasoSgte
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_paso1De1submit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_paso1De1submit"));
	}
	/**
	 * paso1De1submit: with specific test context and state.
	 *		.id : buscarFechasCumplimientoPopup:cbp1:idCmbIrPasoSgte
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_paso1De1submit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_paso1De1submit"), anchor, flags);
	}
	
	/**
	 * TerminarLaTransacciónsubmit: with default state.
	 *		.id : pt2:idComponenteBoton:botonInicio
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_terminarLaTransacciónsu() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_terminarLaTransacciónsu"));
	}
	/**
	 * TerminarLaTransacciónsubmit: with specific test context and state.
	 *		.id : pt2:idComponenteBoton:botonInicio
	 * 		.type : submit
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_terminarLaTransacciónsu(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_terminarLaTransacciónsu"), anchor, flags);
	}
	
	/**
	 * svwBuscarDocumentoRefPopupTRes0IdSelChekt: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:tRes:0:idSelChek::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:tRes:0:idSelChek
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef"));
	}
	/**
	 * svwBuscarDocumentoRefPopupTRes0IdSelChekt: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:tRes:0:idSelChek::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:tRes:0:idSelChek
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef"), anchor, flags);
	}
	
	/**
	 * svwBuscarDocumentoRefPopupItSel0TabSeleccion0TSelecciont: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:0:tabSeleccion:0:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:0:tabSeleccion:0:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef2() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef2"));
	}
	/**
	 * svwBuscarDocumentoRefPopupItSel0TabSeleccion0TSelecciont: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:0:tabSeleccion:0:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:0:tabSeleccion:0:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef2(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef2"), anchor, flags);
	}
	
	/**
	 * svwBuscarDocumentoRefPopupItSel0TabSeleccion1TSelecciont: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:0:tabSeleccion:1:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:0:tabSeleccion:1:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef3() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef3"));
	}
	/**
	 * svwBuscarDocumentoRefPopupItSel0TabSeleccion1TSelecciont: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:0:tabSeleccion:1:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:0:tabSeleccion:1:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef3(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef3"), anchor, flags);
	}
	
	/**
	 * svwBuscarDocumentoRefPopupItSel0TabSeleccion2TSelecciont: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:0:tabSeleccion:2:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:0:tabSeleccion:2:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef4() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef4"));
	}
	/**
	 * svwBuscarDocumentoRefPopupItSel0TabSeleccion2TSelecciont: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:0:tabSeleccion:2:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:0:tabSeleccion:2:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef4(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef4"), anchor, flags);
	}
	
	/**
	 * svwBuscarDocumentoRefPopupItSel1TabSeleccion0TSelecciont: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:1:tabSeleccion:0:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:1:tabSeleccion:0:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef5() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef5"));
	}
	/**
	 * svwBuscarDocumentoRefPopupItSel1TabSeleccion0TSelecciont: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:1:tabSeleccion:0:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:1:tabSeleccion:0:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef5(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef5"), anchor, flags);
	}
	
	/**
	 * svwBuscarDocumentoRefPopupItSel1TabSeleccion1TSelecciont: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:1:tabSeleccion:1:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:1:tabSeleccion:1:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef6() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef6"));
	}
	/**
	 * svwBuscarDocumentoRefPopupItSel1TabSeleccion1TSelecciont: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:1:tabSeleccion:1:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:1:tabSeleccion:1:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef6(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef6"), anchor, flags);
	}
	
	/**
	 * svwBuscarDocumentoRefPopupItSel2TabSeleccion0TSelecciont: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:2:tabSeleccion:0:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:2:tabSeleccion:0:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef7() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef7"));
	}
	/**
	 * svwBuscarDocumentoRefPopupItSel2TabSeleccion0TSelecciont: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:2:tabSeleccion:0:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:2:tabSeleccion:0:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef7(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef7"), anchor, flags);
	}
	
	/**
	 * svwBuscarDocumentoRefPopupItSel2TabSeleccion1TSelecciont: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:2:tabSeleccion:1:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:2:tabSeleccion:1:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef8() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef8"));
	}
	/**
	 * svwBuscarDocumentoRefPopupItSel2TabSeleccion1TSelecciont: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:2:tabSeleccion:1:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:2:tabSeleccion:1:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef8(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef8"), anchor, flags);
	}
	
	/**
	 * svwBuscarDocumentoRefPopupItSel2TabSeleccion2TSelecciont: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:2:tabSeleccion:2:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:2:tabSeleccion:2:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef9() 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef9"));
	}
	/**
	 * svwBuscarDocumentoRefPopupItSel2TabSeleccion2TSelecciont: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:itSel:2:tabSeleccion:2:tSeleccion::content
	 * 		.type : checkbox
	 * 		.value : t
	 * 		.title : 
	 * 		.class : Html.INPUT.checkbox
	 * 		.name : svwBuscarDocumentoRefPopup:itSel:2:tabSeleccion:2:tSeleccion
	 * 		.classIndex : 0
	 */
	protected ToggleGUITestObject checkBox_svwBuscarDocumentoRef9(TestObject anchor, long flags) 
	{
		return new ToggleGUITestObject(
                        getMappedTestObject("checkBox_svwBuscarDocumentoRef9"), anchor, flags);
	}
	
	/**
	 * buscarFechasCumplimientoPopupIdCmlIrAgregarFecha: with default state.
	 *		.text : Agregar Fecha
	 * 		.id : buscarFechasCumplimientoPopup:idCmlIrAgregarFecha
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-compromiso-presupuestario/generarCom ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_buscarFechasCumplimientoP() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_buscarFechasCumplimientoP"));
	}
	/**
	 * buscarFechasCumplimientoPopupIdCmlIrAgregarFecha: with specific test context and state.
	 *		.text : Agregar Fecha
	 * 		.id : buscarFechasCumplimientoPopup:idCmlIrAgregarFecha
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-compromiso-presupuestario/generarCom ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_buscarFechasCumplimientoP(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_buscarFechasCumplimientoP"), anchor, flags);
	}
	
	/**
	 * Compromiso: with default state.
	 *		.text : Compromiso
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenidaInicio?_afrWindowMode=0&_adf.no-new- ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_compromiso() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_compromiso"));
	}
	/**
	 * Compromiso: with specific test context and state.
	 *		.text : Compromiso
	 * 		.href : http://192.168.203.10/sigfe/faces/bienvenidaInicio?_afrWindowMode=0&_adf.no-new- ...
	 * 		.id : 
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_compromiso(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_compromiso"), anchor, flags);
	}
	
	/**
	 * idPgTplIdCmbIrFechasCumplimiento: with default state.
	 *		.text : Agregar fechas de cumplimiento
	 * 		.id : idPgTpl:idCmbIrFechasCumplimiento
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-compromiso-presupuestario/generarCom ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplIdCmbIrFechasCumpl() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplIdCmbIrFechasCumpl"));
	}
	/**
	 * idPgTplIdCmbIrFechasCumplimiento: with specific test context and state.
	 *		.text : Agregar fechas de cumplimiento
	 * 		.id : idPgTpl:idCmbIrFechasCumplimiento
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-compromiso-presupuestario/generarCom ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplIdCmbIrFechasCumpl(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplIdCmbIrFechasCumpl"), anchor, flags);
	}
	
	/**
	 * idPgTplIdCmiIrDocumentoReferencia: with default state.
	 *		.text : Buscar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-compromiso-presupuestario/generarCom ...
	 * 		.id : idPgTpl:idCmiIrDocumentoReferencia
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplIdCmiIrDocumentoRe() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplIdCmiIrDocumentoRe"));
	}
	/**
	 * idPgTplIdCmiIrDocumentoReferencia: with specific test context and state.
	 *		.text : Buscar
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-compromiso-presupuestario/generarCom ...
	 * 		.id : idPgTpl:idCmiIrDocumentoReferencia
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplIdCmiIrDocumentoRe(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplIdCmiIrDocumentoRe"), anchor, flags);
	}
	
	/**
	 * idPgTplIdCmlIrGuardarCompromiso: with default state.
	 *		.text : Guardar Digitado
	 * 		.id : idPgTpl:idCmlIrGuardarCompromiso
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-compromiso-presupuestario/generarCom ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplIdCmlIrGuardarComp() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplIdCmlIrGuardarComp"));
	}
	/**
	 * idPgTplIdCmlIrGuardarCompromiso: with specific test context and state.
	 *		.text : Guardar Digitado
	 * 		.id : idPgTpl:idCmlIrGuardarCompromiso
	 * 		.href : http://192.168.203.10/sigfe/faces/task-flow-compromiso-presupuestario/generarCom ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_idPgTplIdCmlIrGuardarComp(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_idPgTplIdCmlIrGuardarComp"), anchor, flags);
	}
	
	/**
	 * LeyDePresupuestos: with default state.
	 *		.text : Ley de Presupuestos
	 * 		.id : svwBuscarDocumentoRefPopup:idSelonTipoDem::content
	 * 		.title : Ley de Presupuestos
	 * 		.class : Html.SELECT
	 * 		.name : svwBuscarDocumentoRefPopup:idSelonTipoDem
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_leyDePresupuestos() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_leyDePresupuestos"));
	}
	/**
	 * LeyDePresupuestos: with specific test context and state.
	 *		.text : Ley de Presupuestos
	 * 		.id : svwBuscarDocumentoRefPopup:idSelonTipoDem::content
	 * 		.title : Ley de Presupuestos
	 * 		.class : Html.SELECT
	 * 		.name : svwBuscarDocumentoRefPopup:idSelonTipoDem
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_leyDePresupuestos(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_leyDePresupuestos"), anchor, flags);
	}
	
	/**
	 * Nacional: with default state.
	 *		.text : Nacional
	 * 		.id : svwBuscarDocumentoRefPopup:cmb_mpresupuestaria::content
	 * 		.title : Nacional
	 * 		.class : Html.SELECT
	 * 		.name : svwBuscarDocumentoRefPopup:cmb_mpresupuestaria
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_nacional() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_nacional"));
	}
	/**
	 * Nacional: with specific test context and state.
	 *		.text : Nacional
	 * 		.id : svwBuscarDocumentoRefPopup:cmb_mpresupuestaria::content
	 * 		.title : Nacional
	 * 		.class : Html.SELECT
	 * 		.name : svwBuscarDocumentoRefPopup:cmb_mpresupuestaria
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_nacional(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_nacional"), anchor, flags);
	}
	
	/**
	 * RequerimientoPresupuestario: with default state.
	 *		.text : Requerimiento Presupuestario Compromiso Presupuestario
	 * 		.id : svwBuscarDocumentoRefPopup:tipoProcesoBuscarDocRef::content
	 * 		.title : Requerimiento Presupuestario
	 * 		.class : Html.SELECT
	 * 		.name : svwBuscarDocumentoRefPopup:tipoProcesoBuscarDocRef
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_requerimientoPresupuestar() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_requerimientoPresupuestar"));
	}
	/**
	 * RequerimientoPresupuestario: with specific test context and state.
	 *		.text : Requerimiento Presupuestario Compromiso Presupuestario
	 * 		.id : svwBuscarDocumentoRefPopup:tipoProcesoBuscarDocRef::content
	 * 		.title : Requerimiento Presupuestario
	 * 		.class : Html.SELECT
	 * 		.name : svwBuscarDocumentoRefPopup:tipoProcesoBuscarDocRef
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_requerimientoPresupuestar(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_requerimientoPresupuestar"), anchor, flags);
	}
	
	/**
	 * Seleccione: with default state.
	 *		.text : Seleccione... Ingreso Gasto
	 * 		.id : idPgTpl:idSeonchTipoPpto::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchTipoPpto
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione"));
	}
	/**
	 * Seleccione: with specific test context and state.
	 *		.text : Seleccione... Ingreso Gasto
	 * 		.id : idPgTpl:idSeonchTipoPpto::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchTipoPpto
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione"), anchor, flags);
	}
	
	/**
	 * Seleccione: with default state.
	 *		.text : Seleccione... Peso Chileno
	 * 		.id : idPgTpl:idSeonchMonedaPresupuestaria::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchMonedaPresupuestaria
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione2() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione2"));
	}
	/**
	 * Seleccione: with specific test context and state.
	 *		.text : Seleccione... Peso Chileno
	 * 		.id : idPgTpl:idSeonchMonedaPresupuestaria::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeonchMonedaPresupuestaria
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione2(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione2"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id30Menu: with default state.
	 *		.id : idPgTpl:j_id30::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id30Menu() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id30Menu"));
	}
	/**
	 * idPgTplJ_id30Menu: with specific test context and state.
	 *		.id : idPgTpl:j_id30::menu
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id30Menu(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id30Menu"), anchor, flags);
	}
	
	/**
	 * idPgTplJ_id32ScrollContent: with default state.
	 *		.id : idPgTpl:j_id32::ScrollContent
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id32ScrollConte() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id32ScrollConte"));
	}
	/**
	 * idPgTplJ_id32ScrollContent: with specific test context and state.
	 *		.id : idPgTpl:j_id32::ScrollContent
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_idPgTplJ_id32ScrollConte(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_idPgTplJ_id32ScrollConte"), anchor, flags);
	}
	
	/**
	 * pt2ContenedorMsj: with default state.
	 *		.id : pt2:contenedorMsj
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_pt2ContenedorMsj() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_pt2ContenedorMsj"));
	}
	/**
	 * pt2ContenedorMsj: with specific test context and state.
	 *		.id : pt2:contenedorMsj
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_pt2ContenedorMsj(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_pt2ContenedorMsj"), anchor, flags);
	}
	
	/**
	 * _1159: with default state.
	 *		.id : svwBuscarDocumentoRefPopup:seleccionDeInsumo::content
	 * 		.type : text
	 * 		.title : 1.159
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarDocumentoRefPopup:seleccionDeInsumo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__1159() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__1159"));
	}
	/**
	 * _1159: with specific test context and state.
	 *		.id : svwBuscarDocumentoRefPopup:seleccionDeInsumo::content
	 * 		.type : text
	 * 		.title : 1.159
	 * 		.class : Html.INPUT.text
	 * 		.name : svwBuscarDocumentoRefPopup:seleccionDeInsumo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__1159(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__1159"), anchor, flags);
	}
	
	/**
	 * _15022014: with default state.
	 *		.id : idPgTpl:idIndaFechaDocumento::content
	 * 		.type : text
	 * 		.title : 15/02/2014
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:idIndaFechaDocumento
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__15022014() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__15022014"));
	}
	/**
	 * _15022014: with specific test context and state.
	 *		.id : idPgTpl:idIndaFechaDocumento::content
	 * 		.type : text
	 * 		.title : 15/02/2014
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:idIndaFechaDocumento
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text__15022014(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text__15022014"), anchor, flags);
	}
	
	/**
	 * buscarFechasCumplimientoPopupTabFech0IdIndaFechaCumpli: with default state.
	 *		.id : buscarFechasCumplimientoPopup:tabFech:0:idIndaFechaCumpli::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : buscarFechasCumplimientoPopup:tabFech:0:idIndaFechaCumpli
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buscarFechasCumplimientoP() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buscarFechasCumplimientoP"));
	}
	/**
	 * buscarFechasCumplimientoPopupTabFech0IdIndaFechaCumpli: with specific test context and state.
	 *		.id : buscarFechasCumplimientoPopup:tabFech:0:idIndaFechaCumpli::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : buscarFechasCumplimientoPopup:tabFech:0:idIndaFechaCumpli
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buscarFechasCumplimientoP(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buscarFechasCumplimientoP"), anchor, flags);
	}
	
	/**
	 * buscarFechasCumplimientoPopupTabFech0IdInteMonto: with default state.
	 *		.id : buscarFechasCumplimientoPopup:tabFech:0:idInteMonto::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : buscarFechasCumplimientoPopup:tabFech:0:idInteMonto
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buscarFechasCumplimientoP2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buscarFechasCumplimientoP2"));
	}
	/**
	 * buscarFechasCumplimientoPopupTabFech0IdInteMonto: with specific test context and state.
	 *		.id : buscarFechasCumplimientoPopup:tabFech:0:idInteMonto::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : buscarFechasCumplimientoPopup:tabFech:0:idInteMonto
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buscarFechasCumplimientoP2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buscarFechasCumplimientoP2"), anchor, flags);
	}
	
	/**
	 * buscarFechasCumplimientoPopupTabFech1IdIndaFechaCumpli: with default state.
	 *		.id : buscarFechasCumplimientoPopup:tabFech:1:idIndaFechaCumpli::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : buscarFechasCumplimientoPopup:tabFech:1:idIndaFechaCumpli
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buscarFechasCumplimientoP3() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buscarFechasCumplimientoP3"));
	}
	/**
	 * buscarFechasCumplimientoPopupTabFech1IdIndaFechaCumpli: with specific test context and state.
	 *		.id : buscarFechasCumplimientoPopup:tabFech:1:idIndaFechaCumpli::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : buscarFechasCumplimientoPopup:tabFech:1:idIndaFechaCumpli
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buscarFechasCumplimientoP3(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buscarFechasCumplimientoP3"), anchor, flags);
	}
	
	/**
	 * buscarFechasCumplimientoPopupTabFech1IdInteMonto: with default state.
	 *		.id : buscarFechasCumplimientoPopup:tabFech:1:idInteMonto::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : buscarFechasCumplimientoPopup:tabFech:1:idInteMonto
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buscarFechasCumplimientoP4() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buscarFechasCumplimientoP4"));
	}
	/**
	 * buscarFechasCumplimientoPopupTabFech1IdInteMonto: with specific test context and state.
	 *		.id : buscarFechasCumplimientoPopup:tabFech:1:idInteMonto::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : buscarFechasCumplimientoPopup:tabFech:1:idInteMonto
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_buscarFechasCumplimientoP4(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_buscarFechasCumplimientoP4"), anchor, flags);
	}
	
	/**
	 * CP_Licitación: with default state.
	 *		.id : idPgTpl:idInteTituloCompromiso1::content
	 * 		.type : text
	 * 		.title : CP_Licitación
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:idInteTituloCompromiso1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_cP_Licitación() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cP_Licitación"));
	}
	/**
	 * CP_Licitación: with specific test context and state.
	 *		.id : idPgTpl:idInteTituloCompromiso1::content
	 * 		.type : text
	 * 		.title : CP_Licitación
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:idInteTituloCompromiso1
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_cP_Licitación(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cP_Licitación"), anchor, flags);
	}
	
	/**
	 * CP_Licitación: with default state.
	 *		.id : idPgTpl:idInteDescripcionCompromiso::content
	 * 		.title : CP_Licitación
	 * 		.class : Html.TEXTAREA
	 * 		.name : idPgTpl:idInteDescripcionCompromiso
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_cP_Licitación2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cP_Licitación2"));
	}
	/**
	 * CP_Licitación: with specific test context and state.
	 *		.id : idPgTpl:idInteDescripcionCompromiso::content
	 * 		.title : CP_Licitación
	 * 		.class : Html.TEXTAREA
	 * 		.name : idPgTpl:idInteDescripcionCompromiso
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_cP_Licitación2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cP_Licitación2"), anchor, flags);
	}
	
	/**
	 * CPLicitaciónParaPruebasDeRegresion: with default state.
	 *		.id : idPgTpl:idInteDescripcionDocumento::content
	 * 		.title : CP Licitación para pruebas de regresion
	 * 		.class : Html.TEXTAREA
	 * 		.name : idPgTpl:idInteDescripcionDocumento
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_cpLicitaciónParaPruebasDe() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cpLicitaciónParaPruebasDe"));
	}
	/**
	 * CPLicitaciónParaPruebasDeRegresion: with specific test context and state.
	 *		.id : idPgTpl:idInteDescripcionDocumento::content
	 * 		.title : CP Licitación para pruebas de regresion
	 * 		.class : Html.TEXTAREA
	 * 		.name : idPgTpl:idInteDescripcionDocumento
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_cpLicitaciónParaPruebasDe(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cpLicitaciónParaPruebasDe"), anchor, flags);
	}
	
	/**
	 * idPgTplIdInteNumeroDocumento: with default state.
	 *		.id : idPgTpl:idInteNumeroDocumento::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:idInteNumeroDocumento
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplIdInteNumeroDocume() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplIdInteNumeroDocume"));
	}
	/**
	 * idPgTplIdInteNumeroDocumento: with specific test context and state.
	 *		.id : idPgTpl:idInteNumeroDocumento::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:idInteNumeroDocumento
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplIdInteNumeroDocume(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplIdInteNumeroDocume"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrp0IdCmbConceptoInsumoCompromisoItC0Cpc1IdInte: with default state.
	 *		.id : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:0:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:0:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp0IdCmbConcep() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp0IdCmbConcep"));
	}
	/**
	 * idPgTplItAgrp0IdCmbConceptoInsumoCompromisoItC0Cpc1IdInte: with specific test context and state.
	 *		.id : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:0:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:0:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp0IdCmbConcep(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp0IdCmbConcep"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrp0IdCmbConceptoInsumoCompromisoItC1Cpc1IdInte: with default state.
	 *		.id : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:1:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:1:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp0IdCmbConcep2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp0IdCmbConcep2"));
	}
	/**
	 * idPgTplItAgrp0IdCmbConceptoInsumoCompromisoItC1Cpc1IdInte: with specific test context and state.
	 *		.id : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:1:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:1:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp0IdCmbConcep2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp0IdCmbConcep2"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrp0IdCmbConceptoInsumoCompromisoItC2Cpc1IdInte: with default state.
	 *		.id : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:2:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:2:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp0IdCmbConcep3() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp0IdCmbConcep3"));
	}
	/**
	 * idPgTplItAgrp0IdCmbConceptoInsumoCompromisoItC2Cpc1IdInte: with specific test context and state.
	 *		.id : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:2:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:2:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp0IdCmbConcep3(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp0IdCmbConcep3"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrp0IdCmbConceptoInsumoCompromisoItC2Cpc1IdInte: with default state.
	 *		.id : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:2:cpc1:idInteMontoFuturo::con ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:2:cpc1:idInteMontoFuturo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp0IdCmbConcep4() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp0IdCmbConcep4"));
	}
	/**
	 * idPgTplItAgrp0IdCmbConceptoInsumoCompromisoItC2Cpc1IdInte: with specific test context and state.
	 *		.id : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:2:cpc1:idInteMontoFuturo::con ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:0:idCmbConceptoInsumoCompromiso:itC:2:cpc1:idInteMontoFuturo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp0IdCmbConcep4(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp0IdCmbConcep4"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrp1IdCmbConceptoInsumoCompromisoItC0Cpc1IdInte: with default state.
	 *		.id : idPgTpl:itAgrp:1:idCmbConceptoInsumoCompromiso:itC:0:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:1:idCmbConceptoInsumoCompromiso:itC:0:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp1IdCmbConcep() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp1IdCmbConcep"));
	}
	/**
	 * idPgTplItAgrp1IdCmbConceptoInsumoCompromisoItC0Cpc1IdInte: with specific test context and state.
	 *		.id : idPgTpl:itAgrp:1:idCmbConceptoInsumoCompromiso:itC:0:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:1:idCmbConceptoInsumoCompromiso:itC:0:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp1IdCmbConcep(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp1IdCmbConcep"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrp1IdCmbConceptoInsumoCompromisoItC1Cpc1IdInte: with default state.
	 *		.id : idPgTpl:itAgrp:1:idCmbConceptoInsumoCompromiso:itC:1:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:1:idCmbConceptoInsumoCompromiso:itC:1:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp1IdCmbConcep2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp1IdCmbConcep2"));
	}
	/**
	 * idPgTplItAgrp1IdCmbConceptoInsumoCompromisoItC1Cpc1IdInte: with specific test context and state.
	 *		.id : idPgTpl:itAgrp:1:idCmbConceptoInsumoCompromiso:itC:1:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:1:idCmbConceptoInsumoCompromiso:itC:1:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp1IdCmbConcep2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp1IdCmbConcep2"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrp2IdCmbConceptoInsumoCompromisoItC0Cpc1IdInte: with default state.
	 *		.id : idPgTpl:itAgrp:2:idCmbConceptoInsumoCompromiso:itC:0:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:2:idCmbConceptoInsumoCompromiso:itC:0:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp2IdCmbConcep() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp2IdCmbConcep"));
	}
	/**
	 * idPgTplItAgrp2IdCmbConceptoInsumoCompromisoItC0Cpc1IdInte: with specific test context and state.
	 *		.id : idPgTpl:itAgrp:2:idCmbConceptoInsumoCompromiso:itC:0:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:2:idCmbConceptoInsumoCompromiso:itC:0:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp2IdCmbConcep(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp2IdCmbConcep"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrp2IdCmbConceptoInsumoCompromisoItC1Cpc1IdInte: with default state.
	 *		.id : idPgTpl:itAgrp:2:idCmbConceptoInsumoCompromiso:itC:1:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:2:idCmbConceptoInsumoCompromiso:itC:1:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp2IdCmbConcep2() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp2IdCmbConcep2"));
	}
	/**
	 * idPgTplItAgrp2IdCmbConceptoInsumoCompromisoItC1Cpc1IdInte: with specific test context and state.
	 *		.id : idPgTpl:itAgrp:2:idCmbConceptoInsumoCompromiso:itC:1:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:2:idCmbConceptoInsumoCompromiso:itC:1:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp2IdCmbConcep2(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp2IdCmbConcep2"), anchor, flags);
	}
	
	/**
	 * idPgTplItAgrp2IdCmbConceptoInsumoCompromisoItC2Cpc1IdInte: with default state.
	 *		.id : idPgTpl:itAgrp:2:idCmbConceptoInsumoCompromiso:itC:2:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:2:idCmbConceptoInsumoCompromiso:itC:2:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp2IdCmbConcep3() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp2IdCmbConcep3"));
	}
	/**
	 * idPgTplItAgrp2IdCmbConceptoInsumoCompromisoItC2Cpc1IdInte: with specific test context and state.
	 *		.id : idPgTpl:itAgrp:2:idCmbConceptoInsumoCompromiso:itC:2:cpc1:idInteMontoVigente::co ...
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:itAgrp:2:idCmbConceptoInsumoCompromiso:itC:2:cpc1:idInteMontoVigente
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplItAgrp2IdCmbConcep3(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplItAgrp2IdCmbConcep3"), anchor, flags);
	}
	
	/**
	 * j_password: with default state.
	 *		.id : 
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : j_password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_password() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_password"));
	}
	/**
	 * j_password: with specific test context and state.
	 *		.id : 
	 * 		.type : password
	 * 		.title : 
	 * 		.class : Html.INPUT.password
	 * 		.name : j_password
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_password(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_password"), anchor, flags);
	}
	
	/**
	 * j_username: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : j_username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_username() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_username"));
	}
	/**
	 * j_username: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : j_username
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_j_username(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_j_username"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point PV_GenerarCompromiso_Licitacion object in the SUT.
	 */
	protected IFtVerificationPoint PV_GenerarCompromiso_LicitacionVP() 
	{
		return vp("PV_GenerarCompromiso_Licitacion");
	}
	protected IFtVerificationPoint PV_GenerarCompromiso_LicitacionVP(TestObject anchor)
	{
		return vp("PV_GenerarCompromiso_Licitacion", anchor);
	}
	
	/**
	 * Locate and return the verification point PV_GuardarDigitado_CP object in the SUT.
	 */
	protected IFtVerificationPoint PV_GuardarDigitado_CPVP() 
	{
		return vp("PV_GuardarDigitado_CP");
	}
	protected IFtVerificationPoint PV_GuardarDigitado_CPVP(TestObject anchor)
	{
		return vp("PV_GuardarDigitado_CP", anchor);
	}
	
	

	protected CP_Licitacion_Gastos_Moneda_Nacional_GenerarHelper()
	{
		setScriptName("Modulos.Compromiso.CP_Licitacion_Gastos_Moneda_Nacional_Generar");
	}
	
}

