// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Callscripts;
import LIB.Libreria;
import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PruebaObjetos</b><br>
 * Generated     : <b>2014/08/19 12:29:05</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows XP x86 5.1 <br>
 * 
 * @since  agosto 19, 2014
 * @author ccortes
 */
public abstract class PruebaObjetosHelper extends LIB.Libreria
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox 17.0
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Firefox 17.0
	 * 		.processName : firefox.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * BúsquedaDeAsientosContables: with default state.
	 *		.class : Html.HtmlDocument
	 * 		.title : Búsqueda de Asientos Contables
	 * 		.url : http://192.168.201.33:7001/sigfe/faces/task-flow-completa-variacion-patrimonial/ ...
	 */
	protected DocumentTestObject document_búsquedaDeAsientosCon() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_búsquedaDeAsientosCon"));
	}
	/**
	 * BúsquedaDeAsientosContables: with specific test context and state.
	 *		.class : Html.HtmlDocument
	 * 		.title : Búsqueda de Asientos Contables
	 * 		.url : http://192.168.201.33:7001/sigfe/faces/task-flow-completa-variacion-patrimonial/ ...
	 */
	protected DocumentTestObject document_búsquedaDeAsientosCon(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_búsquedaDeAsientosCon"), anchor, flags);
	}
	
	/**
	 * Seleccione: with default state.
	 *		.text : Seleccione... Ley de Presupuestos Fondos no afectos a Ley
	 * 		.id : idPgTpl:idSeOnChTipoDemanda::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeOnChTipoDemanda
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione"));
	}
	/**
	 * Seleccione: with specific test context and state.
	 *		.text : Seleccione... Ley de Presupuestos Fondos no afectos a Ley
	 * 		.id : idPgTpl:idSeOnChTipoDemanda::content
	 * 		.title : Seleccione...
	 * 		.class : Html.SELECT
	 * 		.name : idPgTpl:idSeOnChTipoDemanda
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_seleccione(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_seleccione"), anchor, flags);
	}
	
	/**
	 * idPgTplDescripcion: with default state.
	 *		.id : idPgTpl:descripcion::content
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : idPgTpl:descripcion
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplDescripcion() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplDescripcion"));
	}
	/**
	 * idPgTplDescripcion: with specific test context and state.
	 *		.id : idPgTpl:descripcion::content
	 * 		.title : 
	 * 		.class : Html.TEXTAREA
	 * 		.name : idPgTpl:descripcion
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplDescripcion(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplDescripcion"), anchor, flags);
	}
	
	/**
	 * idPgTplTitulo: with default state.
	 *		.id : idPgTpl:titulo::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:titulo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplTitulo() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplTitulo"));
	}
	/**
	 * idPgTplTitulo: with specific test context and state.
	 *		.id : idPgTpl:titulo::content
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : idPgTpl:titulo
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_idPgTplTitulo(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_idPgTplTitulo"), anchor, flags);
	}
	
	

	protected PruebaObjetosHelper()
	{
		setScriptName("Callscripts.PruebaObjetos");
	}
	
}

